### ISSUE TITLE
Site de l'OT de Bayonne

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#1]
https://www.visitbayonne.com/fr/pratique/carte-interactive.php#tfo(-GG)=43.566959~-1.63702~43.396566~-1.366482~9&tfo(metaMetaDormir)=|MoMetaDormir|MetaDormir|Classement||-TT&tfo(metaMetaRestaurant)=emptyMeta&tfo(metaMetaVoir)=emptyMeta&tfo(metaMetaAgenda)=emptyMeta

Cela concerne l'attribution.
Je suis perplexe car d'une part il faut "scroller" tout en bas pour la voir, mais cela semble venir de wikimedia maps, cependant si on regarde d'où proviennent les tuiles (f12, réseaux) alors c'est cdn.laetis.fr. Que veux dire cdn ?

**Comment by grischard** [comment]
CDN veut dire « Content distribution network ». Des proxy de distribution, en gros.

**Comment by frodrigo** [comment]
Je ne vois de problème avec le fait que l'attribution soit en bas.

Ce n'est plus possible d'utiliser les tuiles de Wikimedia. "Wikimedia Maps may not be used by third-party services outside of the Wikimedia projects."

Ils ont peut-être ajouté un proxy par-dessus ou utilisent un autre source de tuiles.

Mais vu l'URL des tuiles ça doit être un proxy
https://cdn.laetis.fr/i/leaflet/tiles/https://maps.wikimedia.org/osm-intl/13/4062/2996.png

**Comment by vinber** [comment]
> Je ne vois de problème avec le fait que l'attribution soit en bas.

en fait c'est moi qui me suis effectivement fait avoir, car avec l'aide à droite de l'écran, je pensais être en bas et je n'avais pas compris le scroll.



> Ce n'est plus possible d'utiliser les tuiles de Wikimedia. "Wikimedia Maps may not be used by third-party services outside of the Wikimedia projects."
> 
> Ils ont peut-être ajouté un proxy par-dessus ou utilisent un autre source de tuiles.
> 
> Mais vu l'URL des tuiles ça doit être un proxy
> https://cdn.laetis.fr/i/leaflet/tiles/https://maps.wikimedia.org/osm-intl/13/4062/2996.png

donc c'est le fait d'utiliser wikimedia maps qui n'est pas vraiment normal.

Je clot alors
