### ISSUE TITLE
fnp.huma-num.fr

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#103]
#42
Contactés le 23/10/2021
- [x] https://fnp.huma-num.fr/adws/app/3298f631-53ea-11eb-91f3-dfc85aa511ba/

**Comment by fnicollet** [comment]
Désolé, je n'avais pas vu votre commentaire en Octobre. J'ai ajouté ces copyrights sur le fond OpenTopoMap de ce client

Fabien (Business Geografic)

**Comment by AntoninCurtit** [comment]
Désolé de vous faire travailler à cette heure, aucun souci et merci pour la correction ! 😉👍
