### ISSUE TITLE
Manque attribution, communauté d'agglomération du grand Châtellerault

### ISSUE THREAD

**Issue by Altonss** [osm-fr/attributions#105]
Site de la communauté d'agglomération du grand Châtellerault
Sans attribution

**Description**

- Adresse Web: https://www.grand-chatellerault.fr/connaitre/les-cartes-du-territoire
- Date de prise de contact: pas encore cotacté

**Comment by benoit-dd** [comment]
contact par mail le 13/05/2023: communication@grand-chatellerault.fr

**Comment by cuicui86** [comment]
Problème résolu. L'attribution a été ajouté aux différentes carte présente sur le site.

**Comment by Altonss** [comment]
Merci!
