### ISSUE TITLE
DirectMairie de Adullact n'est pas attribué

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#108]
Exemple ici https://directmairie.adullact.org/issue.

Contact et échange suite à un signalement sur talk il y a un an https://gitlab.adullact.net/directmairie/directmairie/-/issues/113

**Comment by mfaure** [comment]
L'attribution a déjà été codée dans l'appli https://gitlab.adullact.net/directmairie/directmairie/-/commit/3f209a1634cb678bb9f55186e5c98eea64646e7e

Elle sera en ligne à la prochaine mise en production, prévue pour T4-2021 :)

**Comment by vinber** [comment]
yep, merci. On va attendre le déploiement alors :)

**Comment by Dan33l** [comment]
Bonjour @vinber , la version de l'application embarquant le correctif est maintenant en production sur l'instance DirectMairie de l'ADULLACT.

D'autres collectivités peuvent avoir déployé leur propre instance.

**Comment by vinber** [comment]
Bonjour Dan33l, merci
Je constate effectivement la mention, dommage que le lien soit sur OSM et non pas sur https://www.openstreetmap.org/copyright comme proposé dans l'issue sur https://gitlab.adullact.net/directmairie/directmairie/-/issues/113

**Comment by mfaure** [comment]
Bonjour @vinber Merci pour le retour, c'est [corrigé dans le code](https://gitlab.adullact.net/directmairie/directmairie/-/merge_requests/190). Mise en production dans les tuyaux.
