### ISSUE TITLE
[Agence Narobaz]

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#11]
# Agence Drone
https://agence-drone.com/contact
Signalé en décembre 2020
- [x] Corrigé – Carte désactivée

# Camping Le Miroir
https://camping-lemiroir.com/activite/parc-metabief-aventures/
- Signalé en décembre 2020
- [ ] Non corrigé le 14/07/2021

**Comment by cquest** [comment]
Corrigé, je ferme
