### ISSUE TITLE
Encart Qwant Maps dans la recherche de Qwant n'affiche pas immédiatement l'attribution OSM

### ISSUE THREAD

**Issue by Altonss** [osm-fr/attributions#112]
### Ce signalement concerne...

https://www.qwant.com/?q=ugc+paris&t=web

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

- [x] Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
- [X] Une interaction est nécessaire pour afficher l'attribution

### 

- [x] Le responsable a été contacté

### Informations concernant la prise de contact

- Contacté le : 05/11/2021
- Par (email, Twitter...) : Github: https://github.com/Qwant/qwantmaps/issues/162

**Comment by vinber** [comment]
> le problème est résolu

pas tout à fait quand même, il faut toujours une interaction ...

**Comment by Jean-BaptisteC** [comment]
Qwant maps est définitivement éteint, le sujet peut être clos
