### ISSUE TITLE
Conservatoire de Lille, pas d'attribution

### ISSUE THREAD

**Issue by Altonss** [osm-fr/attributions#114]
### Ce signalement concerne...

https://conservatoire.lille.fr/ou-nous-trouver

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

- [ ] Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
- [ ] Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### 

- [ ] Le responsable a été contacté

### Informations concernant la prise de contact

- Contacté le :
- Par (email, Twitter...) :

**Comment by Altonss** [comment]
Les tuiles proviennent de map.telmedia.fr et la réalisation a probablement été faite par https://telmedia.fr/, donc il se peut que beaucoup de sites souffrent de ce même manque d'attribution.
J'ai aussi remarqué que quand on déplace très vite la carte, on voit en bas à droite le copyright leaflet et openstreetmap contributors...donc j'ai l'impression que ça été masqué

**Comment by benoit-dd** [comment]
effectivement, même problème pour https://www.lambersart.fr/les-equipements-sportifs

d'autres sites de la même agence TelMedia ont la bonne attribution: https://www.ville-ronchin.fr/equipements-sportifs
