### ISSUE TITLE
Montpellier Métropole

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#118]
### Ce signalement concerne...

https://www.montpellier3m.fr/cartographie-des-%c3%a9quipements-de-la-m%c3%a9tropole

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

- [ ] Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
- [] Une interaction est nécessaire pour afficher l'attribution (seule la mention OSM Mapnik est affichable après manip sur certaines cartes)

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### 

- [X] Le responsable a été contacté

### Informations concernant la prise de contact

- Contacté le :18/11/2021
- Par messagerie OSM : à [Open Data Montpellier Méditerranée Métropole](https://www.openstreetmap.org/user/Open%20Data%20Montpellier%20M%C3%A9diterran%C3%A9e%20M%C3%A9tropole)
- et via le formulaire de contact du site web 

seule la mention "OSM Mapnik" est visible dans la carte globale des équipements quand on cherche à afficher les couches de données. Aucune mention visible dans les fiches individuelles des équipements (ex https://www.montpellier3m.fr/equipement/mediatheque-jean-giono)

### Commentaire

_Réponse presque immédiate via la messagerie OSM. L'information est remontée au service communication._

**Comment by benoit-dd** [comment]
Réponse plus détaillée le 19/11: 

> Cette carte réalisée il y a plusieurs années, utilise des modules contribués Drupal eux-mêmes branchés sur les tuiles OSM, ces modules n’inclues pas d’options pour le copyright (et ce serait aux auteurs de ces modules qu’ils faudrait s’adresser mais ce sont des modules drupal 7 donc bientôt obsolètes).
> 
> Nous allons refaire la carte avec des modules plus modernes, normalement d’ici la fin de la semaine prochaine ça devrait être réglé.

la [première carte](https://www.montpellier3m.fr/cartographie-des-%c3%a9quipements-de-la-m%c3%a9tropole) semble mise hors ligne (un peu radical comme méthode 😄), les autres sont toujours présentes (par ex https://www.montpellier3m.fr/vivre-sport/reseau-des-piscines) 
Curieusement, ils n'utilisent pas que des cartes OSM ex https://www.montpellier3m.fr/borneselectriques

**Comment by benoit-dd** [comment]
la carte principale est maintenant correctement attribuée. 

restent les cartes individuelles des équipements

**Comment by Jean-BaptisteC** [comment]
Contacté de nouveau ce jour via la messagerie [OSM.org](https://www.openstreetmap.org/messages/1195047)

**Comment by Jean-BaptisteC** [comment]
Réponse de la Métropole ce jour, le problème sera corrigé prochainement (une nouvelle version du site est prévue prochainement)

**Comment by Jean-BaptisteC** [comment]
Problème réglé à ce jour
