### ISSUE TITLE
sites-touristiques-ariege.fr

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#119]
### Ce signalement concerne...

https://www.ariegepyrenees.com/villages-vacances/centre-de-vacances-le-saint-bernard-a-ascou-pailheres/

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

- [ ] Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
- [ ] Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

### 

- [X] Le responsable a été contacté

### Informations concernant la prise de contact

- Contacté le : 21/11/2021
- Par email, à l'adresse du responsable de site.
- Prise de contact également avec l'agence web en charge du site, pour remonter à la source !

**Comment by Altonss** [comment]
Toujours aucune évolution...

**Comment by glacasa** [comment]
Un autre site de la même agence, avec des cartes OpenStreetMap sans attribution : 
https://www.sites-touristiques-ariege.fr/grotte-du-mas-dazil-2/

**Comment by Jean-BaptisteC** [comment]
![image](https://github.com/osm-fr/attributions/assets/87148630/e1ac5672-13ff-4dff-bfd0-fed977ef1dad)

**Comment by vinber** [comment]
sur le lien ci -dessus je n'ai pas PênStreetMap 
![image](https://github.com/osm-fr/attributions/assets/890869/f7b2b31d-e4cd-41f1-aa32-b05f1d82aa47)

**Comment by Jean-BaptisteC** [comment]
Contacté ce jour à l'adresse info@sites-touristiques-ariege.fr et contact@iris-interactive.fr

**Comment by Jean-BaptisteC** [comment]
Retour ce jour par email
![image](https://github.com/user-attachments/assets/6c8779fb-f303-431c-b01a-6b878e3533d9)
