### ISSUE TITLE
TrouverUnLogement.LesCrous.fr

### ISSUE THREAD

**Issue by romain-neil** [osm-fr/attributions#122]
📢 Site pour trouver un logement crous

**Description**

https://trouverunlogement.lescrous.fr/tools/flow/21/search?bounds=-9.9111_54.5899_14.3054_36.8381&page=1&price=60000&residence=b77dac07-0b38-11e8-89ed-005056940822

Pas de contact à ce jour (25/11/2021)

Utilisation de Leafet.js (voir image) ; utilise les serveurs d'OSM

**Comment by tutosfaciles48** [comment]
![image](https://user-images.githubusercontent.com/3512803/143323763-a0eac228-c7d9-46b3-820e-0ddd57f7ab55.png)

**Comment by tutosfaciles48** [comment]
![image](https://user-images.githubusercontent.com/3512803/143323783-d50b190e-74c5-4da3-9d42-aae558655e5b.png)

**Comment by Altonss** [comment]
Résolu :)
