### ISSUE TITLE
billetweb.fr - attribution manquante

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/attributions#128]
Style mapnik osm-fr sans attribution sur https://www.billetweb.fr/

La carte est sur la page de réservation de billets

https://www.billetweb.fr/castaigns-laran&src=agenda

Je n'ai pas pris contact.

**Comment by benoit-dd** [comment]
à noter que sur https://blog.billetweb.fr/boutique-en-ligne (posté en 10/2020) toutes les illustrations semblent avoir la bonne attribution

et que curieusement, le lien vers le "lieu de l'évènement" pointe vers googlemap...

**Comment by Altonss** [comment]
ping @cquest pour les tuiles osm-fr ;)

**Comment by frodrigo** [comment]
Mais il faut commencer par les contacter.

**Comment by Altonss** [comment]
Oups je n'avais pas vu ^

**Comment by benoit-dd** [comment]
Toujours pas d'attribution
Message envoyé par le formulaire de contact de leur site web, avec lien vers cette issue.

**Comment by lefuturiste** [comment]
Il semble que l'apparition soit apparu ?

**Comment by frodrigo** [comment]
Oui !
