### ISSUE TITLE
Les cartes du site de Open Data de la métropole Nice Côte d'Azur ne présentent jamais l'attribution

### ISSUE THREAD

**Issue by Dubs120** [osm-fr/attributions#133]
📢 **Les cartes de visualisation des jeux de données utilisent des tuiles OSM sans attribution**

**Description**
Les différentes cartes visibles sur le site proposent par défaut du fond OSM avec attribution ESRI...
http://opendata.nicecotedazur.org/data/dataset et sous pages pour les données en SIG.
Pour celles où on peut choisir les fonds de carte, le choix enlève la mauvaise attribution, mais ne met JAMAIS celle de OSM pour les fonds OpenStreetMap standard et Transports, toutes les autres ont leur attribution...

Notification du manque de licence par le formulaire en ligne par rubrique [Problème sur un contenu éditorial] et titre explicite "Attribution mention OpenStreetMap absente".
Date 18/12/2021 20h08 (accusé de réception automatique reçu par mail)

**Comment by AdrienHegy** [comment]
Signalement identique à #107
