### ISSUE TITLE
myvalleedejoux.ch

### ISSUE THREAD

**Issue by AntoninDelFabbro** [osm-fr/attributions#135]
⚠ Non contactés

- [ ] https://www.myvalleedejoux.ch/fr/V1124/parcours-col-du-mollendruz-chatel-453

**Comment by benoit-dd** [comment]
carte google, non?

**Comment by AntoninCurtit** [comment]
![image](https://user-images.githubusercontent.com/30950182/147472897-67360297-dc20-45ed-abab-1963769a04ca.png)

Ça a l'apparence de Google, ça utilise du Google, mais le fond de carte est OSM via Thunderforest
Une de leur tuile :
https://tile.thunderforest.com/outdoors/14/8481/5786.png?apikey=2447e5b3e9324ef289b3e50cbdb74ffd

**Comment by Jean-BaptisteC** [comment]
Il utilise maintenant une carte SwissTopo
Et la page suivante https://www.myvalleedejoux.ch/fr/Z14783/itineraires-de-randonnee?length=_all_length utilise le composant leaflet, mais la carte ne s'affiche pas donc impossible de savoir si il utilise osm
