### ISSUE TITLE
Manque d'atribution sur Aladom

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#144]
### Ce signalement concerne...

https://www.aladom.fr/annuaire/pro/2950/

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

- [ ] Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
- [ ] Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

### Le responsable a-t-il été contacté ?

- [X] Le responsable a été contacté

### Informations concernant la prise de contact

- Contacté le : 15 janvier
- Par (email, Twitter...) : formulaire de contact

**Comment by Arnaud-B** [comment]
Bonjour,

La correction a été faites sur nos pages utilisant OpenStreetmap !

Bien sûr, nous n'avons pas fait cela dans le but de nuire à un projet open source (faudrait être assez débile :) )

Dites moi si la correction vous convient (il manque ©, si c'est important pour vous, je le mettrais dans la semaine)

Ps : c'est Aladom, pas Adadom :)

**Comment by Altonss** [comment]
> Dites moi si la correction vous convient (il manque ©, si c'est important pour vous, je le mettrais dans la semaine)

Pour le © je n'en ai aucune idée, je vais laisse les autres plus expérimentés donnés leur avis :)

Merci pour la réactivité :)

**Comment by Arnaud-B** [comment]
@vinber C'est ok pour le © dans l'attribution !

Bonne chance pour faire respecter ça sur les sites qui ne le font pas :) En espérant que la plupart vous réponde vite

**Comment by Altonss** [comment]
Merci beaucoup!
