### ISSUE TITLE
Decathlon Outdoor

### ISSUE THREAD

**Issue by pyrog** [osm-fr/attributions#147]
### Ce signalement concerne...

https://www.decathlon-outdoor.com/fr-fr/solo/le-cernois-drillon-de-lamoura-et-le-refuge-des-adrets-618e2d786a90b

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

- [ ] Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
- [ ] Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Le responsable a-t-il été contacté ?

- [x] Le responsable a été contacté

### Informations concernant la prise de contact

- Contacté le : 18/01/2022
- Par (email, Twitter...) : https://www.decathlon-outdoor.com/fr-fr/contact

<img width="811" alt="Capture d’écran 2022-01-18 à 20 46 34" src="https://user-images.githubusercontent.com/2158081/150007898-38611494-2068-437f-9dbf-4674cf95a605.png">

### Commentaire

Tuiles fournies par Mhikes : https://tiles.mhikes.com/mhikes/15/16929/11606.png

**Comment by Altonss** [comment]
Toujours aucune nouvelle?

**Comment by XandrexOSM** [comment]
Je viens de faire la réclamation via leur formulaire web https://www.decathlon-outdoor.com/fr-fr/contact .
C'est un formulaire Google encapsulé sur leur site.

Pas encore d'acquittement de ma demande.

**Comment by Jean-BaptisteC** [comment]
Corrigé
![Screenshot_20230718-175446](https://github.com/osm-fr/attributions/assets/87148630/38594a91-bce8-447d-9692-40b167e54a75)

**Comment by cayenne17** [comment]
@pyrog, @Altonss : Le problème peut-être fermé ?
