### ISSUE TITLE
mapiful.com

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#15]
**⚠️ Non contactés**

# Site Web
https://www.mapiful.com/editor/
- [ ] L'attribution se trouve derrière un lien « [© Copyright and attribution information](https://www.mapiful.com/terms-condition/) ».

# Posters
- [ ] Les posters ne semblent pas avoir d'attribution.

**Comment by pyrog** [comment]
L'attribution est à la fin d'une ["longue" page](https://www.mapiful.com/terms-condition/) en anglais🙁

### Attribution and copyright to work of others

Some of our products are made possible through the amazing work of the OpenStreetMap community and foundation. They provide us with. OpenStreetMap® is open data, licensed under the Open Data Commons Open Database License (ODbL) by the OpenStreetMap Foundation (OSMF). We support and contribute, and we encourage you to do the same! Get in touch with us if or OSMF if you are interested in contributing.

**Comment by Altonss** [comment]
# Informations supplémentaires

    Responsable contacté le : 13/03/2022
        Par (courriel, Twitter...) : Formulaire du site

L'attribution est présente, dans les règles, mais derrière un lien qui mène vers une autre page.


cf. le commentaire d'origine par @AntoninCurtit sur cette issue: https://github.com/osm-fr/attributions/issues/169#issue-1167678879

**Comment by AntoninCurtit** [comment]
Problème résolu le 15 mars (j'ai traîné...), échange agréable et interlocuteur vraiment très efficace !

> Back when we started this company in 2014 we got in touch with a representatives of the OSM Foundation and talked about how to properly do the attribution without compromising the visual integrity/base of our product. The solution that we came up with together was to include a link on the the OSM copyright webpage in close relation with the map, and also on the physical packaging of the poster - and on top of that we did a corporate sponsorship for the foundation.
>
> However, I can agree with the attribution not being clear so I updated our design tool and added a direct link and attribution, and not only as a sub link on the [Copyright and Attribution page](https://www.mapiful.com/terms-condition/) as before. Please see attached screenshot of the updated editor, as well as the physical product label.
