### ISSUE TITLE
https://bailleur.gorenove.fr/ (CSTB)

### ISSUE THREAD

**Issue by cquest** [osm-fr/attributions#150]
https://bailleur.gorenove.fr/

site du CSTB, utilisant un fond de carte cartodb, de provenance OSM.

- Contacté : ✔️Oui par le formulaire de contact su site

**Comment by haubourg** [comment]
@pascal-schetelat je te taggue ici :)

**Comment by Altonss** [comment]
Parfait, merci beaucoup!
