### ISSUE TITLE
Que faire de mes déchets, manque d'attribution

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#155]
### Ce signalement concerne...

https://quefairedemesdechets.fr/dechet/chaussures

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

- [ ] Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
- [ ] Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Le responsable a-t-il été contacté ?

- [x] Le responsable a été contacté

### Informations concernant la prise de contact

- Contacté le : 2 mars 2022
- Par (email, Twitter...) : page de contact

### Commentaire

je suppose que ce qui est vrai ici pour les chaussures et vrai pour les autres carte.

**Comment by cayenne17** [comment]
en retrant une adresse, c'est affiché.
![image](https://github.com/osm-fr/attributions/assets/47927025/f458f221-23a8-4d89-bae0-54c050b014f9)

 Le lien pointe vers https://www.openstreetmap.org/copyright

Il peut-être fermé @vinber, @Altonss ?
