### ISSUE TITLE
Netatmo Weathermap

### ISSUE THREAD

**Issue by Fabe56** [osm-fr/attributions#164]
### Ce signalement concerne...

La [carte météo](https://weathermap.netatmo.com) de Netatmo qui utilise les données OSM. Par contre, du moins dans sa version mobile, aucune attributions n'est présente.

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Informations supplémentaires

- Netatmo contacté le : 21 novembre 2021
  - Par (courriel, Twitter...) : [Twitter](https://twitter.com/Fabe56/status/1462337437271744514).
- Réponse de leur part le 22 novembre 2021 par [Twitter](https://twitter.com/netatmo/status/1462776461711278081) sans action à ce jour.
- Relance ce 11 mars 2022 toujours via [Twitter](https://twitter.com/Fabe56/status/1502250139515334660).

**Comment by cquest** [comment]
correction déployée ? https://twitter.com/netatmo/status/1504112740901736455

@Fabe56 si oui, tu peux fermer l'ssue :)

**Comment by Fabe56** [comment]
Un bouton Information, à cliquer, a été ajouté pour afficher les attributions sur la page en version mobile.

**Comment by Altonss** [comment]
Je vais rouvrir cette issue, parce qu'il me semble que cela n'est pas considéré comme une attribution suffisante puisqu'une action de l'utilisateur est nécessaire.

**Comment by Fabe56** [comment]
> Je vais rouvrir cette issue, parce qu'il me semble que cela n'est pas considéré comme une attribution suffisante puisqu'une action de l'utilisateur est nécessaire. EDIT: Si quelqu'un a un compte twitter, il peut répondre à Netatmo :)

J'avais effectivement un doute mais je n'ai pas trouvé la documentation qui clarifie ce point. Je peux leur signaler mais cela serait bien d'avoir de quoi les aider à mieux comprendre.

**Comment by Altonss** [comment]
![image](https://user-images.githubusercontent.com/66519591/158640161-51350923-4763-4500-9bf0-9ad95ab28a45.png)
https://www.openstreetmap.org/copyright
C'est assez clair j'ai l'impression, non?

**Comment by Fabe56** [comment]
Cela reste du conditionnel (should) et non une exigence (must), mais j'ai avisé.

**Comment by Altonss** [comment]
Voici la version en anglais, sans doute originale:
![image](https://user-images.githubusercontent.com/66519591/158651938-739b4fb8-23f7-4cc3-a637-96ec5709f7f6.png)

Et voilà ce que me dit deepl.com sur la signification de should:
![image](https://user-images.githubusercontent.com/66519591/158651019-bb87760d-8adc-41b8-949c-76741cff2d62.png)

Donc je ne pense que ce soit si conditionnel que ça, peut-être plutôt une manière polie de dire qu'il faut le faire ainsi ^^ Le français a peut-être été traduit approximativement... je n'en sais rien :smile:

**Comment by Altonss** [comment]
L'attribution semble avoir été corrigée, il est maintenant marqué "OSM Contributors"... Je ne crois toujours pas que ce soit suffisant néanmoins :laughing:

**Comment by NathanBnm** [comment]
Relancé le 11/04/2025 à l'adresse copyright@netatmo.com
