### ISSUE TITLE
ERCC - Emergency Response Coordination Centre (europa.eu)

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/attributions#166]
### Ce signalement concerne...

Le fond de carte est clairement issue des données OSM. J'ai zoomé quelques zones et il n'y a pas de doute.

L'attribution est "[Leaflet](http://leafletjs.com/) | [European Union](http://europa.eu/index_en.htm)"

ERCC - Emergency Response Coordination Centre (European Civil Protection And Humanitarian Aid Operations)
https://erccportal.jrc.ec.europa.eu/

### Présence de l'attribution

❌ Pas d'attribution

**Comment by Altonss** [comment]
Vous avez contacté le site?

**Comment by XandrexOSM** [comment]
J'ai été sur leur site. Dans le footer il y a un lien vers un formulaire web pour les contacter :
https://erccportal.jrc.ec.europa.eu/Home/Contact#/

J'ai essayer de remplir le formulaire mais j'aboutis sur une popup d'échec 

![image](https://user-images.githubusercontent.com/92858966/158069563-d948576d-bf24-4fe2-b8fa-03428de11b8e.png)

Je ne sais pas quels sont les autres moyens de les contacter.

**Comment by XandrexOSM** [comment]
en attendant de trouver un autre moyen de les contacter, je viens d'écrire à leur support en leur demandant des explications.

**Comment by XandrexOSM** [comment]
J'ai eu un retour du support, ils ont fait une modif, l'erreur a changé maintenant.

![image](https://user-images.githubusercontent.com/92858966/158244395-08baea15-255f-40d4-aae0-2c98cc733d6e.png)

(notez la faute de frappe).

Je les ai re-notifiés.

**Comment by Altonss** [comment]
> J'ai eu un retour du support, ils ont fait une modif, l'erreur a changé maintenant.
> 
> ![image](https://user-images.githubusercontent.com/92858966/158244395-08baea15-255f-40d4-aae0-2c98cc733d6e.png)
> 
> (notez la faute de frappe).
> 
> Je les ai re-notifiés.

Ils sont quand même trop fort :rofl:

**Comment by XandrexOSM** [comment]
ok l'erreur avec la faute de frappe n'est pas côté web, elle est du côté de l'appli back-end. Ils ont transmis hier à l'équipe en charge de cette partie.

Quel suspense.

**Comment by Cyrille37** [comment]
Merci pour ces démarches :-)

**Comment by XandrexOSM** [comment]
ça fait un mois et cinq jours. Je viens de les relancer.

**Comment by XandrexOSM** [comment]
J'ai reçu ce matin un email de réponse, _a priori_ pas un email auto :

```
Dear Alexandre,

Thank you for showing us the wrong attribution. We’ll do the necessary asap.

Best,

Nelles for ERCC portal
```

**Comment by XandrexOSM** [comment]
Je viens de regarder, c'est mis à jour.

![image](https://user-images.githubusercontent.com/92858966/169523047-7f8ff6a5-8f0a-46d8-93ed-be79fa909717.png)

**Comment by XandrexOSM** [comment]
@Cyrille37 pouvez-vous clôturer cette "issue" s'il vous plaît ?

**Comment by Cyrille37** [comment]
Avec grand plaisir @XandrexOSM 
et mille mercis pour les démarches :-)
