### ISSUE TITLE
mapiful.com

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#169]
### Ce signalement concerne...

- [ ] https://www.mapiful.com/editor/#/editor

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

Il y a un lien vers openstreetmap.org/copyright, Le responsable a été contacté, Une interaction est nécessaire pour afficher l'attribution

### Informations supplémentaires

- Responsable contacté le : 13/03/2022
  - Par (courriel, Twitter...) : Formulaire du site

L'attribution est présente, dans les règles, mais derrière un lien qui mène vers une autre page.

**Comment by Altonss** [comment]
N'est-ce pas un doublon de https://github.com/osm-fr/attributions/issues/15 ?

**Comment by AntoninCurtit** [comment]
Ben c'est carrément un doublon en fait, moi qui dit toujours qu'il faut vérifier que l'issue n'existe pas déjà... Merci de ta vigilance ! 😉💪‍

**Comment by Altonss** [comment]
> Ben c'est carrément un doublon en fait, moi qui dit toujours qu'il faut vérifier que l'issue n'existe pas déjà... Merci de ta vigilance ! wink💪‍

En plus c'était la tienne ^^

**Comment by vinber** [comment]
> > Ben c'est carrément un doublon en fait, moi qui dit toujours qu'il faut vérifier que l'issue n'existe pas déjà... Merci de ta vigilance ! wink💪‍
> 
> En plus c'était la tienne ^^

cela me fait du bien de voir que je ne suis pas le seul a m'autodoublonner :)
