### ISSUE TITLE
👋 Vinci Autoroute

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#170]
### Ce signalement concerne...

la carte sur la page https://www.vinci-autoroutes.com/fr/mon-trajet/ est attribué Mapbox, mais pas de mention d'OSM.

à noter que les autres cartes du site 
https://www.vinci-autoroutes.com/fr/autoroutes-temps-reel/
https://www.vinci-autoroutes.com/fr/previsions-trafic/
sont correctement attribuées (mais Leaflet plutôt que Mapbox)

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Informations supplémentaires

- Responsable contacté le : 18/03/2022
  - Par Twitter : MP
- Lié au signalement : #

**Comment by benoit-dd** [comment]
réponse le 22/04 via twitter
> Bonjour et merci ! nous avons transmis votre message
> Nous allons procéder à la modification nécessaire. Elle sera disponible courant mai (dans une dizaine de jours) !

pas de modif pour l'instant, 

- [ ] à vérifier à la fin du mois

**Comment by AntoninCurtit** [comment]
→ Attribution correcte constatée
Good, je clos ?

**Comment by Altonss** [comment]
> https://www.vinci-autoroutes.com/fr/autoroutes-temps-reel/
> https://www.vinci-autoroutes.com/fr/previsions-trafic/

C'est deux liens sont presques correctement attribués, j'ai juste noté qu'il manquait le lien/ou l'indication de la licence. Mais ce n'est qu'un détail :)

**Comment by AntoninCurtit** [comment]
Tu es aussi maniaque que moi et aussi frustré à l'idée qu'on ferme l'issue sans que ça soit corrigé... :') Mais le temps & énergie investis à batailler ne le sont pas à contribuer à l'amélioration des données OSM... Si ça peut consoler. 😇

**Comment by Altonss** [comment]
Je voulais juste l'ajouter pour être complet sur l'inventaire :)
