### ISSUE TITLE
horaire-et-annuaire.fr

### ISSUE THREAD

**Issue by AntoninDelFabbro** [osm-fr/attributions#173]
### Ce signalement concerne...

- [ ] https://horaire-et-annuaire.fr/fiche/pharmacie/4230-pharmacie-saint-benigne-pontarlier.html

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.fr

### Informations supplémentaires

- Lié au signalement : #167

**Comment by Jean-BaptisteC** [comment]
Le site est toujours down
Je ferme l'issue
