### ISSUE TITLE
SNCF Carte interactive du réseau ferré français

### ISSUE THREAD

**Issue by danieldegroot2** [osm-fr/attributions#175]
### Ce signalement concerne...

- [SNCF - Carte interactive du réseau ferré français](https://www.sncf-reseau.com/fr/carte/carte-interactive-reseau-ferre-francais-0)

Pas comme autres cartes interactives SNCF sur un carte Esri web, mais un carte Esri integré, avec attribution OSM (correcte..) sans lien copyright.

(signalement ajouté par GitHub web); @Altonss @AntoninCurtit s'il vous plait `attribution sans lien copyright` `Non contacté` `Tuiles osm.org`

### Présence de l'attribution

✔️ Avec attribution

### Vérifications

Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté le : -
  - Par (courriel, Twitter...) : - (peut utiliser courriel)
- Lié au signalement : -

**Comment by Altonss** [comment]
Dans les conditions d'attribution il est noté "Vous pouvez mentionner ceci avec un lien hypertexte vers [cette page de mentions légales](https://www.openstreetmap.org/copyright)." Donc inutile de s'attarder sur ce genre de soucis pour l'instant, alors qu'il existe de nombreux sites où l'attribution n'existe même pas
