### ISSUE TITLE
https://moisson-live.com/

### ISSUE THREAD

**Issue by cquest** [osm-fr/attributions#18]
URL concernée: https://moisson-live.com/

Le gestionnaire du site semble être https://comparateuragricole.com/contact

Le message suivant a été envoyé le 16 juillet 2021:

> Bonjour,
> 
> Vous semblez être à l'origine de la carte visible sur https://moisson-live.com/
> 
> Cette carte utilise un fond basé sur OpenStreetMap, mais l'attribution de celle-ci manque comme indiqué sur https://openstreetmap.org/copyright
> 
> Merci de faire le nécessaire.

**Comment by lmagreault** [comment]
Efficace le marquage. C'est corrigé.

**Comment by cquest** [comment]
Oui, je viens de le retirer.
