### ISSUE TITLE
👋 abc-map.fr

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/attributions#180]
### Ce signalement concerne...

Outil libre de création de carte à la u-map.

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

### Informations supplémentaires

https://gitlab.com/abc-map/abc-map/-/issues/5

**Comment by AntoninCurtit** [comment]
Quelques pistes fournies par la [Fondation](https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines) concernant l'attribution :

- immediately with a dismiss interaction, for example clicking an ‘x’ in the corner of a dialog
- automatically on map interaction such as panning, clicking, or zooming
- automatically after five seconds. This also applies to splash screens or pop-ups.

**Comment by Altonss** [comment]
(Juste un petit détail aussi, tant qu'on y est: il faut aussi ajouter un lien vers https://www.openstreetmap.org/copyright ou mentionner la license:
Voilà ce que dit précisément cette page:
> Vous devez également préciser clairement que les données sont disponibles sous la licence ODbL (Open Database License) et, si vous utilisez les tuiles de notre carte, que la carte est sous la licence CC BY-SA. Vous pouvez mentionner ceci avec un lien hypertexte vers [cette page de mentions légales](https://www.openstreetmap.org/copyright).

)

**Comment by remipassmoilesel** [comment]
Je vais améliorer l'affichage des attributions. Etant donné que l'app est utilisable sur beaucoup plusieurs tailles d'écran, et étant donné que les attributions peuvent être nombreuses, je vais afficher les attributions dans le coin haut gauche. Si j'ai bien compris les docs ce coin est une option. 

Comme attribution je vais conserver `© OpenStreetMap contributors` pour les données OSM comme indiqué sur les docs.

Je rétablirais aussi l'utilisation d'attributions en HTML pour qu'il y ai un lien sur les cartes navigables.

**Comment by Altonss** [comment]
Tout semble parfait maintenant, merci! Je vais donc fermer l'issue :)
