### ISSUE TITLE
justice.fr

### ISSUE THREAD

**Issue by AntoninDelFabbro** [osm-fr/attributions#182]
### Ce signalement concerne...

- [ ] https://www.justice.fr/annuaire/tribunal-judiciaire-besan%C3%A7on

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

**Comment by XandrexOSM** [comment]
Bonjour @AntoninCurtit ,

je viens de faire la réclamation via leur formulaire de contact, rubrique "signaler un problème technique". Je n'ai pas encore eu d'accusé de réception email de mon signalement.

Pouvez-vous s'il vous plaît changer le tag de cette _issue_ de "Non contacté" à "Contacté" ?

**Comment by XandrexOSM** [comment]
Je viens de recevoir l'acquittement par email : 

>  Bonjour,
> 
> Nous avons bien pris en compte votre demande [ticket n° DEM_220520_117]. Celle-ci est en cours de traitement par le service support.
> 
> Nous reviendrons vers vous dans les meilleurs délais afin d’apporter une réponse à votre demande.
> 
> Ce message est une réponse automatique, vous ne pouvez pas y répondre.
> 
> Cordialement,
> 
> L’équipe support

**Comment by nlehuby** [comment]
Bonjour,

je les ai contacté ce jour, également via le formulaire de contact, rubrique "signaler un problème technique".

**Comment by vinber** [comment]
c'est énorme, la justice qui enfreint la loi :)

**Comment by nlehuby** [comment]
> Bonjour,
> 
> je les ai contacté ce jour, également via le formulaire de contact, rubrique "signaler un problème technique".

J'ai reçu une réponse, envoyée depuis ne-pas-repondre@justice.gouv.fr : 
```
Bonjour,

Votre courrier électronique n'entre pas dans le périmètre d'information du portail [Justice.fr](https://justice.fr/).

Bien cordialement,

L’équipe support
```

**Comment by XandrexOSM** [comment]
je viens de m'apercevoir que suite à ma demande, et après l'accusé de réception, ils m'ont répondu le 23 mai 2022, mais à côté de la plaque : 

```
Bonjour,

Nous vous informons que le site [Justice.fr](https://justice.fr/) n'est pas un site de conseils juridiques.

Nous vous invitons à vous rapprocher d'un tribunal afin qu'il vous fournisse une liste des structures proposant des consultations juridiques gratuites.

Vous pouvez aussi vous rendre dans un point justice qui accueille gratuitement et anonymement les personnes rencontrant un problème juridique et/ou administratif.

Pour trouver le point-justice près de chez vous, vous pouvez contacter le 30 39.

Depuis la page d'accueil [Justice.fr](https://justice.fr/) , vous avez accès à la rubrique [Accès au droit](https://www.justice.fr/acces-droit) .

Bien cordialement,

L’équipe support
```

**Comment by cquest** [comment]
J'ai renvoyé un message avant signalement sur https://github.com/openstreetmap/tile-attribution/issues pour blocage :

> Bonjour,
> Nous sommes heureux de voir que votre site fait usage d'un fond de carte provenant d'OpenStreetMap comme ici: https://www.justice.fr/annuaire/tribunal-judiciaire-besan%C3%A7on
> Cependant, cet utilisation est soumise à une condition, indiquer clairement dans un coin de la carte la provenance de celle-ci comme expliqué sur https://osm.org/copyright
> Cette attribution est manquante et vous a été signalée dans le passé (avril 2022) sans effet à ce jour. Merci de procéder à cet ajout, à défaut le service de fond de carte pourra être suspendu.

**Comment by grischard** [comment]
Merci tous! Bloqués ici: https://github.com/openstreetmap/tile-attribution/issues/68

**Comment by NathanBnm** [comment]
J'ai voulu les relancer à ce sujet mais le formulaire de contact ne fonctionne pas.

<img width="499" alt="Capture d’écran 2024-10-02 à 10 18 50" src="https://github.com/user-attachments/assets/6f486bb9-bf80-4f45-9bc7-2c8ab0a6db54">

J'avais repris le message de @cquest :

```
Bonjour,

Nous sommes heureux de voir que votre site fait usage d'un fond de carte provenant d'OpenStreetMap comme ici : https://www.justice.fr/annuaire/tribunal-judiciaire-caen

Cependant, cet utilisation est soumise à une condition, indiquer clairement dans un coin de la carte la provenance de celle-ci comme expliqué sur https://osm.org/copyright

Cette attribution est manquante et vous a été signalée dans le passé (avril 2022) sans effet à ce jour.

Ainsi l'accès au service de fond de carte sur votre site a été suspendu par la fondation en septembre 2024.

Si vous souhaitez rétablir l'accès au service. Merci de procéder à l'ajout.
```

**Comment by cquest** [comment]
Oh... une réponse !

> Veuillez nous excuser pour le délai de traitement de votre demande. L'équipe projet justice.fr travaille sur la résolution du problème de copyright. Nous reviendrons vers vous une fois le problème corrigé.

Y'a pas à dire, la justice est lente en France... plus de 3 mois pour répondre.

**Comment by cquest** [comment]
Nouveau mail, la correction est faite et sera bientôt en production.

**Comment by atchisson** [comment]
ça semble corrigé.. à moitié ? 
![image](https://github.com/user-attachments/assets/823974a4-5cc0-41ae-8cf4-8d021f8efbdf)

**Comment by Jean-BaptisteC** [comment]
Le fond de carte est de nouveau disponible, je clos le ticket
