### ISSUE TITLE
Bebee Market

### ISSUE THREAD

**Issue by danieldegroot2** [osm-fr/attributions#183]
### Ce signalement concerne...

[Bebee Market](https://bebee.market/) ([Example](https://bebee.market/bebee-market/public/market/vival-livres-orpierre))
- Service: Leaflet
- Tuiles: Mapbox Streets
- Data: OpenStreetMap

Seulement d'attribution Leaflet. Pas d'attribution visible en console web (F12). Pas d'attribution dans mentions légales.

Editeur website par [mentions légals](https://bebee.market/bebee-market/public/legal-mentions); Email : contact@excellencie.com
("Nous contacter" en footer retourne aussi un email possiblement. Mais je n'ai pas le configuré.)

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

`Non contacté`

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Informations supplémentaires

(_Quelque commerces en cet website semble non verifié, le website est peut etre pas 'vrai' ou simplement a pas de verification suffisant pour ca._)

**Comment by benoit-dd** [comment]
contacté par mail: contact@excellencie.com le 13/05/2023

**Comment by Jean-BaptisteC** [comment]
Site indispo
