### ISSUE TITLE
https://ceseranupes.fr/

### ISSUE THREAD

**Issue by Altonss** [osm-fr/attributions#185]
### Ce signalement concerne...

- [ ] https://ceseranupes.fr/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Informations supplémentaires

- Responsable contacté le : 
  - Par (courriel, Twitter...) : 
- Lié au signalement : #

Il me semble que le fond de carte est issue de données OSM: https://carto.com/basemaps/

**Comment by Jean-BaptisteC** [comment]
Le site est indispo
