### ISSUE TITLE
https://www.cartoradio.fr/ - ANFR

### ISSUE THREAD

**Issue by cayenne17** [osm-fr/attributions#187]
### Ce signalement concerne...

- [x] https://www.cartoradio.fr/index.html#/cartographie/stations
- [x] https://www.cartoradio.fr/index.html#/cartographie/mesures
- [x] https://www.cartoradio.fr/index.html#/cartographie

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

**Comment by flacombe** [comment]
Il y a tout de même ce contrôle affichant OSM dans le coin inférieur gauche.

N'est-ce pas déjà un début ?
![image](https://user-images.githubusercontent.com/5690599/193416845-6b562cac-9f4e-42a7-9800-bf2b1d13c164.png)

**Comment by cayenne17** [comment]
> 

ça y était déjà effectivement, ça sert à passer du Plan IGN, Image satellite IGN et OSM.

**Comment by cayenne17** [comment]
> Il y a tout de même ce contrôle affichant OSM dans le coin inférieur gauche.
> 
> N'est-ce pas déjà un début ? ![image](https://user-images.githubusercontent.com/5690599/193416845-6b562cac-9f4e-42a7-9800-bf2b1d13c164.png)

ça y était déjà effectivement. ça sert à passer du Plan IGN, Satellite IGN et OSM

**Comment by benoit-dd** [comment]
message envoyé au prestataire qui a créé le site: Atol : contact@atolcd.com le 13/05/2023

**Comment by benoit-dd** [comment]
réponse par mail, correction prévue pour la prochaine mise à jour.

Ils disent intégrer systématiquement les attributions, exemple donné https://remocra-recette.atolcd.show/remocra/#hydrants/localisation (rendu OSM-FR? attribution pas tout à fait conforme lien vers openstreetmap.org au lieu de openstreetmap.org/copyright)

**Comment by cayenne17** [comment]
je vois que ça a été rajouté en bas à droite avec un lien hypertext : 
![image](https://github.com/osm-fr/attributions/assets/47927025/41336b46-6c4f-4fb6-a43f-7ec64670afa1)

Par contre, il n'y a pas "contributors".

Est-ce que je laisse ouvert ou je peux fermer ?

@flacombe , @benoit-dd

**Comment by flacombe** [comment]
Pour ma part c'est suffisant, je laisse les autres s'exprimer.

**Comment by benoit-dd** [comment]
pareil, on peut fermer

**Comment by cayenne17** [comment]
Je ferme le problème

**Comment by cayenne17** [comment]
> > Je ferme le problème
> > PS : @Altonss Comment rajouter/retirer les tags ?
> 
> Je crois qu'il faut avoir plus de droits sur le dépôt pour pouvoir modifier les tags. On peut laisser les tags en l'état, puisque l'issue étant fermée cela revient à dire que le problème est résolu.

pas de tag "Attribution après interaction" ?

**Comment by cayenne17** [comment]
> Non, j'arrive à voir l'attribution sans interaction (ce tag concerne les attributions visibles seulement après une interaction sur le site) :)

OK, c'est pas ce que j'avais compris de l'utilité du tag.
