### ISSUE TITLE
Cartographie France Tiers-Lieux

### ISSUE THREAD

**Issue by lefuturiste** [osm-fr/attributions#198]
### Ce signalement concerne...

- [Toute les pages autres que la page d'accueil sur cartographie.francetierslieux.fr](https://cartographie.francetierslieux.fr/#?tags=Fablab%20/%20Atelier%20de%20Fabrication%20Num%C3%A9rique) 

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

MapBox

### Informations supplémentaires

L'attribution est présente sur la [page principale](https://cartographie.francetierslieux.fr/), mais dès qu'on fait une interaction pour ajouter un filtre ou un tag ou alors si on arrive sur le site via un lien comme https://cartographie.francetierslieux.fr/#?tags=Fablab%20/%20Atelier%20de%20Fabrication%20Num%C3%A9rique alors l'attribution n'est plus là. Il s'agit très probablement d'un bug graphique involontaire.

- Responsable contacté le : Pas encore contacté

**Comment by vinber** [comment]
Contacté Benoit, qui travaille à FTL ce jour

**Comment by vinber** [comment]
alors en fait Benoit ne travaille pas à FTL (je le précise si il revient lire ce mot :) ) mais transmis à qui de droit cependant :)

**Comment by flacombe** [comment]
Des news à ce propos ?

L'attribution n'est pas visible sur la carte indiquée

**Comment by vinber** [comment]
je viens de relancer 3 personnes en leur signalant (de nouveau) cette issue.

**Comment by FlorentLivin** [comment]
Bonjour,
Merci pour ce retour. Il s'agit d'une problématique d'affichage. L'attribution ne "disparaît" pas en tant que telle, elle dépasse de l'écran vers le bas, le conteneur du filtre la décalant. Je tâche de m'occuper de ce problème d'affichage au plus vite.
Encore merci et au plaisir d'échanger sur nos outils prochainement.

**Comment by vinber** [comment]
Bonjour, merci pour le retour et de venir en discuter ici, c'est super.

je ne suis pas sur de comprendre, je n'arrive pas à voir l'attribution même si je "descend" vers le bas ? Mais disons que l'enjeu n'est pas que j'arrive à la voir, c'est qu'elle soit visible donc quand tu as pu "régler" le souci, n'hésite pas à le signaler ici pour que l'on ferme l'issue.

**Comment by FlorentLivin** [comment]
Résolu !

**Comment by vinber** [comment]
merci @FlorentLivin je constate la même chose, je ferme l'issue !
