### ISSUE TITLE
monnaie-libre.fr

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#200]
### Ce signalement concerne...

- [x] https://monnaie-libre.fr/

### Présence de l'attribution

❌ Pas d'attribution

**Comment by Altonss** [comment]
Peut-être ping @ManUtopiK qui semble peut-être a même de pousser une correction directement sur les sources du site ici : https://git.duniter.org/websites/monnaie-libre-fr :)

**Comment by ManUtopiK** [comment]
Corrigé !
