### ISSUE TITLE
cartes sur touraineloirevalley.com

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/attributions#205]
### Ce signalement concerne...

Les cartes sur [touraineloirevalley.com](https://www.touraineloirevalley.com/)

Par exemple : https://www.touraineloirevalley.com/itineraires/boucle-pedestre-n14-entre-indre-et-loire-brehemont/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté le : 03/07/2022
  - Par formulaire sur le site
- Lié au signalement : #

![image](https://user-images.githubusercontent.com/368965/177040356-27b79e39-51a7-4a95-b4a1-97116be794f3.png)

**Comment by benoit-dd** [comment]
agence IRIS : #28

**Comment by vinber** [comment]
attribué 

![image](https://github.com/user-attachments/assets/864d48b8-2a4c-43ac-b77e-a70ace0fe976)
