### ISSUE TITLE
Vélitul - Laval Aglo sans attribution

### ISSUE THREAD

**Issue by Altonss** [osm-fr/attributions#211]
### Ce signalement concerne...

- [ ] https://www.agglo-laval.fr/utile-au-quotidien/transports-et-mobilites/lagglo-a-velo/velitul

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté le : Pas encore contacté
  - Par (courriel, Twitter...) : 
- Lié au signalement : #

**Comment by Kalepom** [comment]
Je remarque que l'attribution figure dans les Mentions légale https://www.agglo-laval.fr/autres/mentions-legales, mais pas sur les cartes

**Comment by vinber** [comment]
mail envoyé ce jour en utilisant le mail contact qui permet d'écrire à valerie.deneux[@]agglo-laval.fr

**Comment by Kalepom** [comment]
Je vois qu'un encart a été ajouté sous la carte

**Comment by Altonss** [comment]
> Je vois qu'un encart a été ajouté sous la carte

Merci, ça a l'air bon maintenant :)
