### ISSUE TITLE
century21.fr

### ISSUE THREAD

**Issue by tr19h9z5f6z63g5** [osm-fr/attributions#215]
### Ce signalement concerne...

- la carte des apparts de https://www.century21.fr/projet-immobilier/

l'attribution est présente mais cachée par le bandeau de droite qui vient par défaut, et qui n'est pas fermé intuitivement 

le fournisseur est tile.bienici.com

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

**Comment by Jean-BaptisteC** [comment]
L'attribution est visible même si le bandeau est ouvert
![image](https://github.com/osm-fr/attributions/assets/87148630/508f149e-7f57-48ad-a215-194dee807adc)
