### ISSUE TITLE
👋 Citymapper

### ISSUE THREAD

**Issue by le-jun** [osm-fr/attributions#217]
### Ce signalement concerne...

- [Applications mobiles iOs – et Android ? – Citymapper](https://citymapper.com/) 

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Informations supplémentaires

Bien qu’utilisant le fond de carte Google, l’application – vérifié sous iOS – indique explicitement faire usage d’OpenStreetMap comme source de données parmi une grande liste accessible via les menus. Dans ce genre de cas, est-ce que l’attribution colle avec nos demandes ou pas ?

**Comment by vdct** [comment]
OSM est indiqué avec un lien vers la page de copyright. Tant qu'on ne trouve pas de contextes avec de la donnée OSM affichée mais sans crédit, l'état actuel est suffisant.

**Comment by Altonss** [comment]
> OSM est indiqué avec un lien vers la page de copyright. Tant qu'on ne trouve pas de contextes avec de la donnée OSM affichée mais sans crédit, l'état actuel est suffisant.

Je peux donc fermer cette issue pour le moment?

**Comment by vdct** [comment]
Oui
