### ISSUE TITLE
👋 Carte Morzine Dépliant 

### ISSUE THREAD

**Issue by Djiril** [osm-fr/attributions#222]
### Ce signalement concerne...

Carte de la ville de Morzine sur un dépliant.

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fournisseur de tuiles ?

Autre/inconnu

### Informations supplémentaires

- Responsable contacté le : 14 août 2022
- Par courriel : jacky.beucher@jbcarto.com

![9CCE28E5-5209-4C81-9061-1B881D30F2F0](https://user-images.githubusercontent.com/64784806/184543651-a0a1feef-30cb-402b-abe3-316d57ff77a4.jpeg)

**Comment by Altonss** [comment]
Êtes vous sûr qu'il s'agit de données OSM?

**Comment by Djiril** [comment]
﻿
En tout cas la carte est fortement inspirée par OSM…
Ce qui m’a mis la puce à l’oreille c’est la représentation de la rivière :









Ensuite il y a des représentations de bâtiments assez similaires :









Après je peux me tromper mais c’est fortement inspiré d’OSM, qu’en pensez vous ?


Cyril / Djiril

**Comment by Djiril** [comment]
J’ai répondu par mail j’ai l’impression que les photos ne sont pas passées voici donc deux exemples sur la représentation de la rivière : 

![D7115662-918E-46B2-A361-85EEB0362220](https://user-images.githubusercontent.com/64784806/184551048-e6c3e5fe-13bb-45e0-a863-3c6b8892e637.jpeg)

![12EE42CE-F8D3-4EF8-8AAE-991DDCE4705C](https://user-images.githubusercontent.com/64784806/184551061-9cd6ac59-46fd-4482-bf30-c500de23fb94.png)

![CC026EA2-A7FB-4FD4-94BE-1153BD787C9A](https://user-images.githubusercontent.com/64784806/184551074-a96b59b0-d22e-46ed-9bd6-a7eae9c30254.jpeg)

![71694DE4-AB5D-4FE6-B1E2-9D04770926C8](https://user-images.githubusercontent.com/64784806/184551083-fc82199b-3e4f-472f-ba2c-f494dc8c2a33.png)

**Comment by Altonss** [comment]
> J’ai répondu par mail j’ai l’impression que les photos ne sont pas passées voici donc deux exemples sur la représentation de la rivière :
> 
> ![D7115662-918E-46B2-A361-85EEB0362220](https://user-images.githubusercontent.com/64784806/184551048-e6c3e5fe-13bb-45e0-a863-3c6b8892e637.jpeg)
> 
> ![12EE42CE-F8D3-4EF8-8AAE-991DDCE4705C](https://user-images.githubusercontent.com/64784806/184551061-9cd6ac59-46fd-4482-bf30-c500de23fb94.png)
> 
> ![CC026EA2-A7FB-4FD4-94BE-1153BD787C9A](https://user-images.githubusercontent.com/64784806/184551074-a96b59b0-d22e-46ed-9bd6-a7eae9c30254.jpeg)
> 
> ![71694DE4-AB5D-4FE6-B1E2-9D04770926C8](https://user-images.githubusercontent.com/64784806/184551083-fc82199b-3e4f-472f-ba2c-f494dc8c2a33.png)

Je ne suis pas du tout expert, mais ça me semble très proche aussi !

**Comment by elmevess** [comment]
Le tracé de la rivière est un import (ou un décalquage à la main?) du cadastre qui n'a pas été modifié manuellement après dans les zones mentionnées. le way de la rivière date du cadastre de 2009 d'après la source du groupe de modification.
![2022-08-21 16_30_52-Window](https://user-images.githubusercontent.com/111694298/185796108-862db5fe-d4f1-47e6-ad59-9fc58708d3b6.png)
![2022-08-21 16_31_21-Window](https://user-images.githubusercontent.com/111694298/185796109-24f7b474-e3b0-4664-9307-4f4e58a0c19c.png)
Il serait intéressant d'essayer de trouver des zones avec des similarités que l'on puisse attribuer à un groupe de modification précis sur OSM, et qui ne soit pas issu d'une autre source.

**Comment by Djiril** [comment]
Merci @elmevess pour la vérification, effectivement c'est plus compliqué que je ne pensais...

**Comment by benoit-dd** [comment]
Quelques autres indices qui pour moi indiquent que la carte n'est pas basée sur OSM:
La [Route du Plan](https://www.openstreetmap.org/way/96358789/history) s'est toujours appelée comme ça sur OSM, alors qu'elle apparait comme "Chemin du du Plan" (Sic)
Le chemin d'Ombers présent sur le plan, n'existait pas sur OSM avant que tu ne l'y ajoutes (w1084433628)

**Comment by Djiril** [comment]
Ok merci pour tous vos commentaires je ferme l'issue
