### ISSUE TITLE
voyage.aprr.fr/carte-itineraires

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#230]
### Ce signalement concerne...

- [ ] https://voyage.aprr.fr/carte-itineraires

### Présence de l'attribution

❌ Pas d'attribution

**Comment by flacombe** [comment]
Bizarre ce fond ViaMichelin qui semble bien reprendre des géométries OSM.

Qu'en penses-tu @vdct ?

**Comment by Altonss** [comment]
> Bizarre ce fond ViaMichelin qui semble bien reprendre des géométries OSM.

Les tiles viennent en fait de Mapbox si on regarde en détail :)

**Comment by flacombe** [comment]
C'est la foire à la saucisse !

**Comment by flacombe** [comment]
Contact effectué
https://twitter.com/InfosReseaux/status/1576226560650010634

**Comment by flacombe** [comment]
L'attribution a été rajoutée ce jour !
https://voyage.aprr.fr/carte-itineraires

Un ticket en moins :)
