### ISSUE TITLE
Blog scani

### ISSUE THREAD

**Issue by Altonss** [osm-fr/attributions#237]
### Ce signalement concerne...

- [ ] https://blog.scani.fr/index.php/2022/10/02/ouverture-de-la-fibre-a-joigny/

### Présence de l'attribution

❌ Pas d'attribution

### Informations supplémentaires

- Responsable contacté le : 
  - Par (courriel, Twitter...) : 
- Lié au signalement : #

**Comment by Jean-BaptisteC** [comment]
Contacté ce jour à l'adresse contact@scani.fr
Concerne aussi le site https://www.scani.fr/

**Comment by Jean-BaptisteC** [comment]
![image](https://github.com/user-attachments/assets/10ccc267-c6f6-4b3c-9160-1191302d876d)

C'est corrigé
