### ISSUE TITLE
mairie-lhoumeau.fr

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#24]
⚠️ Non contactés

- [ ] Pas d'attribution
http://www.mairie-lhoumeau.fr/fr/equipements-municipaux

**Comment by AntoninCurtit** [comment]
#25

**Comment by Jean-BaptisteC** [comment]
Contacté à l'adresse support.neopse@inedi.fr

**Comment by matkoniecz** [comment]
map spotted on https://mairie-lhoumeau.fr/fr/gl/1413934/geolocalisation-209

**Comment by Jean-BaptisteC** [comment]
Retour ce jour du support Neopse, le site sera corrigé prochainement

**Comment by ElementW** [comment]
« prochainement » mais c'est toujours inchangé 🙄

**Comment by Jean-BaptisteC** [comment]
Relance ce jour
