### ISSUE TITLE
inforoute.le64.fr - Pas d'attrib

### ISSUE THREAD

**Issue by nicogodet** [osm-fr/attributions#249]
### Ce signalement concerne...

http://inforoute.le64.fr/

Tuile .org, pas d'attribution

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

Non contacté

**Comment by Jean-BaptisteC** [comment]
La mention a été rajoutée
![image](https://github.com/osm-fr/attributions/assets/87148630/73bfb848-43b5-4765-98a7-94a0484c8a13)
