### ISSUE TITLE
Carte interactive de Cherbourg

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#250]
### Ce signalement concerne...

https://www.cherbourg.fr/carte-interactive-1303.html

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

Une interaction est nécessaire pour afficher l'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

**Comment by AdrienHegy** [comment]
Le lien du signalement ne fonctionne plus.
https://www.cherbourg.fr/carte-interactive/ fonctionne.
Il n’affiche plus de fond OSM mais un fond IGN (sans attribution mais ça ne nous concerne plus)
Je pense qu’on peut fermer le ticket.
