### ISSUE TITLE
Site mairie Onet le château 

### ISSUE THREAD

**Issue by Yod4z** [osm-fr/attributions#253]
Sur les pages des évènements il y a une carte pour montrer l'emplacement et il n'y a pas d'attribution et je ne sais pas où est hébergé la carte.
Exemple : https://www.onet-le-chateau.fr/evenements/grand-quine-football-onet-le-chateau/

Email envoyé au service communication de la commune  sans réponse à ce jour.

**Comment by Yod4z** [comment]
Je viens de relancer une demande via la page de contact du site ainsi que au prestataire ayant réalisé le site

**Comment by Yod4z** [comment]
La réponse de leur service est que la licence est mentionnée sur la page des licenses https://www.onet-le-chateau.fr/mentions-legales/
Il me semble que la licence osm doit être visible sur la carte affichée, non?

**Comment by Yod4z** [comment]
Il faut le lié à [Stratis](https://github.com/osm-fr/attributions/issues/27)

**Comment by Altonss** [comment]
> Il me semble que la licence osm doit être visible sur la carte affichée, non?

Pas forcément, mais il faut qu'il faut créditer Openstreetmap de manière appropriée dans un coin de la carte par ex (en l'affichant comme indiqué par OSM) et soit afficher la licence, soit avoir un lien vers la page https://www.openstreetmap.org/copyright , c'est du moins ce que j'ai compris...

**Comment by Altonss** [comment]
Le problème est résolu :)
