### ISSUE TITLE
Vidéo Au coeur d'une centrale hydroélectrique par EDF/Les Frères Poulain

### ISSUE THREAD

**Issue by flacombe** [osm-fr/attributions#259]
### Ce signalement concerne...

Dans une vidéo réalisée il y a deux ans, Les Frères Poulain utilisent à plusieurs reprises un rendu OSM (difficile à déterminer lequel) pour situer géographiquement l'emplacement des lieux filmés.
https://www.youtube.com/watch?v=zZtL3Cy7S0U

La vidéo concerne une centrale électrique construite par EDF dans la vallée de la Romanche.

Les vues OSM sont visibles aux instant suivants
* Entre 2:08 et 2:12
* Entre 5:58 et 6:02
* Entre 13:13 et 13:18

En particulier, la géométrie de la galerie d'amenée ressort sur ces rendus
https://www.openstreetmap.org/way/233913701

D'autant plus dommage que les éléments fournis par EDF sont correctement crédités.

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### Informations supplémentaires

- Responsable contacté par mail le 22/12

**Comment by Altonss** [comment]
@flacombe On peut fermer cette issue puisque il n'est plus possible de changer qqch et que les réalisateurs ont été contacté?

**Comment by flacombe** [comment]
Dommage, mais soit.

**Comment by elmevess** [comment]
Le commentaire épinglé de l'auteur commence par l'attribution OpenStreetMap avec les time code, on peut pas le louper quand on entre dans l'espace commentaire. C'est le mieux qu'on puisse avoir je pense.

**Comment by flacombe** [comment]
Dans l'état actuel oui, c'est bien ce que je leur ai dit. C'est dommage que Youtube ne permette plus de mettre des liens directement dans la vidéo comme passé un temps.

Cela aurait été comparable aux mentions "Source EDF" là où c'est bien affiché à d'autres moments dans la vidéo.
