### ISSUE TITLE
Géofoncier public

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#260]
### Ce signalement concerne...

- https://public.geofoncier.fr/app/

lorsque l'on choisit carte, c'est un fond osm provenant des serveurs de la fondation

![image](https://user-images.githubusercontent.com/890869/210640263-8852f596-a47c-4095-a490-bf4d048d65bb.png)

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté plusieurs fois par mail pour la question des données OSM et Blue parking (documenté ici https://forum.openstreetmap.fr/t/geometres-expert-100k-places-pmr-blue-parking-pour-le-3-decembre-2021/7414/23)

je fais un rappel blue parking et attributions pour débuter 2023

**Comment by Ltrlg** [comment]
Quand je passe la souris au-dessus de l’icône « i » en face de « Carte », une infobulle « Source : OpenStreetMap » s’affiche.

**Comment by Ltrlg** [comment]
Il ne s’agissait pas de sous-entendre que c’était suffisant (la première chose que j’ai pensé en le voyant est d’ailleurs que c’est probablement cassé sur les écrans sans souris). Je signalais seulement que « Pas d'attribution » ne correspondait pas à ce que j’avais vu.

**Comment by vinber** [comment]
Bien vu @Ltrlg , effectivement je n'avais pas vu, je change le tag, merci

**Comment by Thibtib51** [comment]
J'ai profité d'un de leur post sur LinkedIn pour le faire un rappel.

**Comment by AdrienHegy** [comment]
Le lien du signalement renvoit une erreur 404.
https://public.geofoncier.fr/ fonctionne.
En choisissant le fond de carte, il ne me semble plus y avoir de fond OSM, seulement un fond IGN (sans attribution, mais ça ne nous concerne plus).
Je pense qu’on peut fermer le ticket.
