### ISSUE TITLE
www.cmonsite.fr

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#264]
### Ce signalement concerne...

- [ ] https://www.cmonsite.fr/
  - [ ] Exemple : https://www.fengshuiconseil-harmonie.com/contact.html

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.fr

**Comment by Jean-BaptisteC** [comment]
Il n'y a plus de carte OSM sur la page contact du site mentionné en exemple
