### ISSUE TITLE
agglo-seine-eure.fr

### ISSUE THREAD

**Issue by lefuturiste** [osm-fr/attributions#268]
### Ce signalement concerne...

https://www.agglo-seine-eure.fr/carto/

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté le : 2023-02-15
  - Par formulaire de contact sur site web : https://www.agglo-seine-eure.fr/formulaire-de-contact/
- Lié au signalement : #27

**Comment by lefuturiste** [comment]
2023-03-09 12:45 - Relance par email à agglo@seine-eure.com faute d'adresse email plus précise du service de com

**Comment by lefuturiste** [comment]
2023-03-20 09:15 - Relance par email à communication@seine-eure.com

**Comment by lefuturiste** [comment]
Réponse reçu le 2023-03-21 16:46 de Pauline VASSEUR, chargée de communication digitale. 
Conversation e-mail en cours.

**Comment by AdrienHegy** [comment]
Qu’est-ce qui avait justifié la réouverture du ticket ?
Les attributions me semblent correctes à ce jour pour cette page (versions ordinateur et mobile).
Par contre il reste toujours le souci identifié dans #307 pour cette agglomération.

**Comment by lefuturiste** [comment]
Il existe toujours des pages sans attributions :


Voici quelques exemples d'URL problématiques :

https://www.agglo-seine-eure.fr/decisions-bureau-conseil-agglo/

https://www.agglo-seine-eure.fr/equipements/centre-aquatique-aquaval/

https://www.agglo-seine-eure.fr/equipements/decheterie-vironvay/

https://www.agglo-seine-eure.fr/equipements/mini-reseau/

https://www.agglo-seine-eure.fr/acceder-hotel-agglomeration-services-techniques/

https://www.agglo-seine-eure.fr/equipements/gymnase-andre-malraux/

https://www.agglo-seine-eure.fr/equipements/patinoire/

https://www.agglo-seine-eure.fr/histoire-agglo/

**Comment by AdrienHegy** [comment]
Ok ! En effet, merci !
Du coup j’ajoute https://www.agglo-seine-eure.fr/carte-atoumod-deplacements/ à la liste et je ferme l’autre ticket pour éviter le doublon.

**Comment by Jean-BaptisteC** [comment]
Toutes les pages mentionnées ont une attribution, je ferme le ticket
