### ISSUE TITLE
[Agence Telmedia]

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#271]
### Ce signalement concerne...

https://telmedia.fr/

### Présence de l'attribution

❌ Pas d'attribution

**Comment by benoit-dd** [comment]
message envoyé par leur formulaire de contact le 13/05/2023

**Comment by benoit-dd** [comment]
réponse reçue, c'est corrigé sur tous les cas cité, et intégré désormais à leur standards pour leur productions futures.

(il restera peut-être des absences sur des références plus anciennes?)

**Comment by Altonss** [comment]
> réponse reçue, c'est corrigé sur tous les cas cité, et intégré désormais à leur standards pour leur productions futures.
> 
> (il restera peut-être des absences sur des références plus anciennes?)

Merci beaucoup!
