### ISSUE TITLE
ville-marsannay-la-cote.fr

### ISSUE THREAD

**Issue by AntoninDelFabbro** [osm-fr/attributions#272]
### Ce signalement concerne...

- [ ] https://www.ville-marsannay-la-cote.fr/salle-henri-berger-1

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Il y a un lien vers openstreetmap.org/copyright, Une interaction est nécessaire pour afficher l'attribution

### Informations supplémentaires

- Les tuiles cachent l'attribution.
- Lié au signalement : #271

**Comment by benoit-dd** [comment]
contacté (cf ticket telmedia), réponse reçue, c'est corrigé
