### ISSUE TITLE
Manque d'attribution sur Carrément Fleurs

### ISSUE THREAD

**Issue by Kalepom** [osm-fr/attributions#278]
### Ce signalement concerne...

- Les pages magasins du réseau de fleuristes Carrément Fleurs affichent une carte sur fond OSM sans attribution (par ex. : https://www.carrementfleurs.com/nos-magasins/46-anglet.html)

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté le : 05/03/2023
  - Par courriel : contact@carrementfleurs.com

**Comment by Jean-BaptisteC** [comment]
Ils sont passées sur un fond de plan Google, je ferme le ticket
