### ISSUE TITLE
Application météo Windy.com

### ISSUE THREAD

**Issue by PtiBzh** [osm-fr/attributions#281]
### Ce signalement concerne...

https://play.google.com/store/apps/details?id=com.windyty.android
Les fonds de carte Outdoor et Winter Sports (visible en zoomant) utilisent des données OSM.

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

Autre/inconnu

### Informations supplémentaires

- Responsable contacté le : 
  - Par (courriel, Twitter...) : 
- Lié au signalement : #

**Comment by Altonss** [comment]
Le site web https://www.windy.com/ est bien attribué sur desktop, et sur mobile l'attribution est visible après interaction dans le menu.

**Comment by Altonss** [comment]
> ###
> 
> https://play.google.com/store/apps/details?id=com.windyty.android Les fonds de carte Outdoor et Winter Sports (visible en zoomant) utilisent des données OSM.

Avez-vous regardé si l'attribution figure en bas du menu hamburger (3 barres) dans l'application?

**Comment by PtiBzh** [comment]
![Screenshot_20230310-124335](https://user-images.githubusercontent.com/3416635/224307702-74851c35-2c5c-4c82-9dd3-4bae47ceecf3.png)
Merci pour l'info.
Je clôture.

**Comment by Altonss** [comment]
Je l'ai quand même classé dans "Attribution après interaction"
