### ISSUE TITLE
Ballon de Paris Generai

### ISSUE THREAD

**Issue by slasherfun** [osm-fr/attributions#288]
### Ce signalement concerne...

- https://ballondeparis.com/infos-pratiques

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté le : 2 avril 2023
  - Par (courriel, Twitter...) : formulaire de contact du site
- Lié au signalement : #

**Comment by Jean-BaptisteC** [comment]
L'attribution a été ajouté
![image](https://github.com/osm-fr/attributions/assets/87148630/f060afce-9d21-4baf-bc09-92d2aa6882df)

**Comment by slasherfun** [comment]
Pas de réponse au courriel, mais corrigé, donc je clos.
