### ISSUE TITLE
Attribution à peine visible (https://sedeplacer.bordeaux-metropole.fr/)

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#294]
### Ce signalement concerne...

- [ ] sur la carte https://sedeplacer.bordeaux-metropole.fr/
- [ ] l'attribution en bas à gauche est coupé à moitié, pas de lien, ...

### Présence de l'attribution

❌ Pas d'attribution

### Informations supplémentaires

Pas de contact pris

**Comment by Altonss** [comment]
Sur mobile quasi invisible...

**Comment by Lyokolux** [comment]
Contacté le 2023-05-22
Destinataire:

Objet: Manque d'attribution appropriée à OpenStreetMap

>Bonjour,
>
>En tant que contributeur à OpenStreetMap, je suis content(e)e
voir que vous utilisez une carte issue d'OpenStreetMap sur votre site [sedeplacer.bordeaux-metropole.fr](http://sedeplacer.bordeaux-metropole.fr/)plus particulièrement sur la page d'accueil https://sedeplacer.bordeaux-metropole.fr/.
>Cependant, j'ai noté que la carte n'est pas correctement attribuée. En effet,
nous demandons que votre crédit comporte la mention « © les contributeurs
d’OpenStreetMap ». Vous devez également préciser clairement que les données sont
disponibles sous la licence ODbL. Vous pouvez mentionner ceci avec un lien
hypertexte vers https://www.openstreetmap.org/copyright.
>
>Une attribution correcte permet de préciser les sources de la carte ou des
données ainsi que ce que les utilisateurs ont le droit d'en faire.
>
>Si vous avez besoin d'aide pour effectuer la correction ou si vous avez des
questions, ne pas hésiter à répondre à ce message ou à utiliser un de nos canaux
de communication : https://wiki.openstreetmap.org/wiki/FR:Canaux_de_contact.
>
>Enfin, une attribution correcte permet de diffuser l'existence d'OpenStreetMap,
d'attirer de nouvelles contributions et d'étendre la communauté. C'est
extrêmement important pour améliorer la qualité de la base de données en qui
vous et des millions de personnes font confiance.
>
>Lorsque la correction aura été faite, n'hésitez pas à me le signaler.
>
>Merci.

**Comment by Lyokolux** [comment]
Réponse recu lundi

<blockquote>
Bonjour,

 

Votre demande a bien été prise en compte.

La carte que vous avez signalé est une ancienne carte qui va être très prochainement remplacée par une nouvelle plus complète et plus fonctionnelle. Elle proposera toujours un fond de plan OpenStreetMap avec les crédits et mentions correctes comme vous  l’avez indiqué.

 

Cordialement,

Stéphane Verdier

..........................................................

Webmaster / Chargé de projets Web

LEWEB - Direction Communication

Bordeaux Métropole
</blockquote>

**Comment by Jean-BaptisteC** [comment]
L'attribution est plus visible (et c'est un lien cliquable)
![image](https://github.com/osm-fr/attributions/assets/87148630/4440f87d-536f-4bd2-ad6a-b7669dbce37b)

**Comment by vinber** [comment]
ouah @Jean-BaptisteC tu te fais une tournée de tous les sites :) merci
