### ISSUE TITLE
POP Mérimée

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#296]
### Ce signalement concerne...

[POP : la plateforme ouverte du patrimoine ](https://www.pop.culture.gouv.fr/notice/merimee/PA52000017)
ex: https://www.pop.culture.gouv.fr/notice/merimee/PA52000017

minicarte de localisation des monuments historiques:

Mapbox, attribution avec interaction (et l'attribution pointe vers https://www.openstreetmap.org/about/ au lieu de https://www.openstreetmap.org/copyright/)

### Présence de l'attribution

⚠️ Attribution partielle

### Vérifications

Une interaction est nécessaire pour afficher l'attribution

### Informations supplémentaires

- Responsable non contacté

**Comment by vdct** [comment]
> l'attribution pointe vers https://www.openstreetmap.org/about/ au lieu de https://www.openstreetmap.org/copyright/

Je ne comprends pas en quoi c'est un problème, le lien /about donne lui-même accès au lien /copyright et indique en plus un peu de contexte sur le projet, ce qui ne peut pas faire de mal quand on découvre OSM pour la 1ere fois suite à un clic dans un coin de fond de carte...

**Comment by Lyokolux** [comment]
Il y a bien le `@ OpenStreetMap` aussi

**Comment by benoit-dd** [comment]
On est d'accord que la page about est sans doute plus accessible pour expliquer ce qu'est OSM et générer de nouveaux contributeurs

Mais la page https://wiki.osmfoundation.org/wiki/Licence/Attribution_Guidelines indique que le lien doit pointer vers /copyright. Donc tant qu'à demander une correction, autant tout faire dans les règles 
La [page d'attribution de Mapbox ](https://docs.mapbox.com/help/getting-started/attribution/) semble d'ailleurs maintenant donner les bonnes informations.

Je ne sais pas si le code mis à disposition par Mapbox est aujourd'hui corrigé pour pointer par défaut correctement, ou s'ils n'ont mis à jour que cette page et laissent leurs utilisateurs se débrouiller pour que ça se passe bien... (voir par ex sujet #130 )



à noter toujours sur le même site, que quand la carte est en grand, il n'y a pas besoin d'interaction pour afficher l'attribution
https://www.pop.culture.gouv.fr/search/map

**Comment by Jean-BaptisteC** [comment]
Maintenant l'attribution est affichée par défaut avec le lien vers la page copyright
