### ISSUE TITLE
Défault d'attribution page contacts site CICB GLH

### ISSUE THREAD

**Issue by 7tonin** [osm-fr/attributions#299]
### Ce signalement concerne...

- [ ] CIBC Gard Lozère Hérault https://www.cibcglh.fr/index.php/contacts

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

- Responsables contactés le 27 mai 2023 : 
  - Par courriel : aux deux agences propriétaires du site, Nîmes, Alès, (cf. page contacts) ; copie à l'agence de communication éditrice du site, DIMDT (cf. mentions légales) [dimdt.com est un domaine désuet, d'où transfert à un membre de dimdt identifié dans la coopérative Mine de talents https://www.minedetalents.fr/profil-entrepreneur/242-jerome-arbeit/]
- Lié au signalement : #
- Technologie : intégration d'un module Joomla!

**Comment by Jean-BaptisteC** [comment]
L'attribution à été corrigé
![image](https://github.com/osm-fr/attributions/assets/87148630/5056a08e-dcce-414b-ab78-991a0f6a77d2)

**Comment by 7tonin** [comment]
Chouette !
Il y a même une mention en bas de page où se trouvent les quatre carte interactives.
