### ISSUE TITLE
Bulletin d'information de la ville de Figeac - défaut d'attribution

### ISSUE THREAD

**Issue by 7tonin** [osm-fr/attributions#300]
### Ce signalement concerne...

- [ ] en pages 6 et 7 du bulletin de février 2023, un fond de carte est utilisé pour présenter le déploiement du réseau de chaleur de la ville. https://ville-figeac.fr/votre-mairie/mairie-figeac/informations-municipales-bulletins

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Le responsable a été contacté

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

- Responsable contacté le 8 mars 2023 : 
  - Par courriel : (j'y prenais l'exemple d'un plan sur leur site où OpenStreetMap était correctement crédité https://ville-figeac.fr/plan-interactif)
  - Réponse le 9 mars de la personne en charge de la communication.
```
Nous avons pris note de vos remarques.

Je tiens à vous préciser que ce plan nous a été transmis par le service Communication du SYDED du Lot qui ne nous a pas indiqué de crédit particulier à préciser. Je leur ai transmis votre mail pour information.

A l’avenir, afin de remédier à cet oubli, nous serons vigilants et nous nous renseignerons bien sur l’origine de la base du plan lorsque nous en utiliserons un dans le Bulletin Municipal. 
```
- Lié au signalement : #301

**Comment by Jean-BaptisteC** [comment]
A rouvrir si de nouveau cas, se produise dans des prochaines versions du magazine
