### ISSUE TITLE
ONLY LYON https://www.lyon-france.com/

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#303]
### Ce signalement concerne...

(signalé sur https://forum.openstreetmap.fr/t/possible-utilisation-sans-attribution/3474/5? mais non remonté encore ici)

[ONLYLYON Tourisme et Congrès](https://www.lyon-france.com/) office de tourisme de Lyon
par exemple sur les pages thématiques
https://www.lyon-france.com/je-decouvre-lyon/culture-et-musees/musees

ou sur celles des éléments individuels
https://www.lyon-france.com/je-decouvre-lyon/culture-et-musees/musees/musee-d-art-contemporain-mac
https://www.lyon-france.com/je-decouvre-lyon/restaurants-et-gastronomie/label-bouchons-lyonnais/daniel-et-denise-saint-jean

### Présence de l'attribution

❌ Pas d'attribution

### Informations supplémentaires

- Responsable non contacté

**Comment by benoit-dd** [comment]
source Mapbox, mais même l'attribution Mapbox est volontairement masquée.
![image](https://github.com/osm-fr/attributions/assets/52233014/e9467cb0-a056-4188-92fa-f9240b96f503)

**Comment by Jean-BaptisteC** [comment]
Ils ont changés, ils utilisent maintenant maptiler
![image](https://github.com/osm-fr/attributions/assets/87148630/8328648c-98d2-447a-a937-de10cee69d42)
