### ISSUE TITLE
Réseau de transport en commun Cap Cotentin

### ISSUE THREAD

**Issue by AdrienHegy** [osm-fr/attributions#305]
### Ce signalement concerne...

- Le site https://plans.capcotentin.fr/fr/ utilise un fond OpenStreetMap. Une surcouche de POI interactive est également disponible et j’y retrouve un amenity=bicycle_parking que j’ai renseigné hier soir (avec les mêmes renseignements). Les mentions s’affichent correctement sur mobile. Sur ordinateur (Firefox, ArchLinux) elles sont masquées derrière le footer (mais présentes dans le code source). Les tuiles sont fournies par le prestataire instant-system.

### Présence de l'attribution

❌ Pas d'attribution

### Informations supplémentaires

Non contacté en attendant de documenter les soucis d’attribution du syndicat mixte/prestataire ici.

- Lié au signalement : #304 (partie prenante au syndicat mixte et même distributeur de tuile)

**Comment by flacombe** [comment]
Contact du fournisseur de tuiles instant-system cet après-midi.
L'attribution est en effet absente. Il faut noter qu'ils produisent leur propre tuiles, sans mobiliser les ressources bénévoles associatives ou personnelles. Cela n'empêche rien sur le besoin d'attribution mais nous rencontrons ce cas plutôt rarement.

A suivre pour le compte rendu de nos échanges.

**Comment by jmlaurenti** [comment]
Bonjour @AdrienHegy, et merci à @flacombe pour l'échange très constructif de cet après-midi. 
Chez Instant-System nous sommes dans une phase de bascule vers une utilisation des tuiles vectorielles (via un serveur tileserver-gl hébergé par nos soins) pour en faire profiter l'ensemble de nos clients (dont Cap Cotentin, Palmbus, Atoumod et quelques autres listés ici même). 
Malheureusement et nous le regrettons fortement, nos sites actuels (qui utilisent depuis quelques semaines des serveurs de tuiles OSM raster également hébergés dans notre infra) ont deux bugs signalés par ailleurs (bandeau qui recouvre les mentions, et taille des caractères trop petite).
Nous allons donc accélérer la bascule vers du vectoriel, avec une mise à jour des sites qui corrigera les problèmes ci-dessus, pour respecter pleinement les règles d'attribution des outils. 
Comme convenu, nous reviendrons signaler ici ces mises à jour.
Cordialement, JML

**Comment by jmlaurenti** [comment]
Bonjour @AdrienHegy @flacombe , pour vous signaler que nous (Instant-System) avons mis à jour le site [https://plans.capcotentin.fr/fr/](https://plans.capcotentin.fr/fr/) pour qu'il utilise notre serveur de tuiles vectorielles.
Le bug d'affichage du copyright OSM a été fixé.
Je vous laisse vérifier que tout soit bien conforme à la charte :-)

Nous travaillons sur les autres sites signalés, je mettrais à jour les tickets correspondants dès nos déploiements terminés.

Cordialement,
JML

**Comment by flacombe** [comment]
Bonjour @jmlaurenti 

Merci beaucoup pour le feedback. C'est pour ainsi dire une première pour moi où nous interagissons directement avec l'utilisateur dans ces tickets. C'est une très bonne chose.

Le problème me semble réglé pour ce territoire. Je laisse @AdrienHegy clore ce ticket.

**Comment by AdrienHegy** [comment]
En effet, tout semble bon pour ce ticket. Merci pour votre réactivité et votre retour.
