### ISSUE TITLE
Transports agglomération Seine-Eure

### ISSUE THREAD

**Issue by AdrienHegy** [osm-fr/attributions#307]
### Ce signalement concerne...

- La page https://www.agglo-seine-eure.fr/carte-atoumod-deplacements/ utilise un fond OSM sans les attributions. (la page https://www.agglo-seine-eure.fr/carto/ présente les bonnes attributions).

### Présence de l'attribution

❌ Pas d'attribution

### Informations supplémentaires

Non contacté en attendant de documenter les soucis d’attribution du syndicat mixte/prestataire ici.

- Lié au signalement : #304 (même syndicat mixte)

**Comment by AdrienHegy** [comment]
Service communication de l’agglomération et éditeur (Stratis) contactés par mail aujourd’hui (17/10/2023)

**Comment by AdrienHegy** [comment]
Stratis m’indique par mail ne plus être le titulaire du marché de maintenance du site.
L’agglomération était également destinataire du mail de contact.

**Comment by Jean-BaptisteC** [comment]
La mention a été ajoutée sur le carte mentionnée dans le premier lien
![image](https://github.com/osm-fr/attributions/assets/87148630/f91719f4-e96a-481a-9d69-a141bd1458bb)

**Comment by AdrienHegy** [comment]
![image](https://github.com/osm-fr/attributions/assets/95868023/ed0571f6-572b-42e3-a445-2fb6555f3715)
Sur la version « mobile » du site, les mentions sont effectivement présentes.
Par contre, je ne les vois pas sous Firefox sur mon PC (ArchLinux). Ni en simulant un iPad avec les outils Firefox (confirmé par un utilisateur d’iPad).
Après approfondissement avec les outils Firefox, elles semblent être masquées derrière le bouton « Accéder à la carte interactive »

**Comment by AdrienHegy** [comment]
Et bien je ne m’explique pas la différence de comportement…
Par contre je reviens sur ce que j’ai dis, c’est un problème de taille de la div id="map" a priori. En désactivant les contraintes sur la hauteur ou l’overflow, les mentions apparaissent.
Pour le reste, je ne dispose pas des connaissances/compétences nécessaires pour aller plus loin.

**Comment by AdrienHegy** [comment]
Fusionné dans #268
