### ISSUE TITLE
Réseau de transport en commun Palmbus (Cannes Pays de Lérins)

### ISSUE THREAD

**Issue by AdrienHegy** [osm-fr/attributions#309]
### Ce signalement concerne...

- Le site https://www.palmbus.fr/fr/recherche-ditineraire-/177 utilise un fond OSM sans attribution. Les tuiles sont distribuées par cityway.

### Présence de l'attribution

❌ Pas d'attribution

### Informations supplémentaires

Non contacté en attendant de documenter les soucis d’attribution du syndicat mixte/prestataire ici.

- Lié au signalement : #304 (parmi les clients affichés par le prestataire instant-system et tuiles citiway)

**Comment by Jean-BaptisteC** [comment]
OSM est mentionné lorsqu'on sélectionne le calque

**Comment by Jean-BaptisteC** [comment]
Ici
![image](https://github.com/osm-fr/attributions/assets/87148630/ad1c1e26-a1c2-41cc-a026-b1858d1e260a)

**Comment by vinber** [comment]
ok, pour moi c'est juste la sélection de calque, cela n'a pas de lien avec la mention d'attribution :)

**Comment by AdrienHegy** [comment]
Cityway et le gestionnaire de réseau ont été contactés dans le cadre de l’issue #324, par courrier le 16/10/2023

**Comment by AdrienHegy** [comment]
[Document numérisé.pdf](https://github.com/osm-fr/attributions/files/13879901/Document.numerise.pdf)
Réponse par courrier

**Comment by AdrienHegy** [comment]
![image](https://github.com/osm-fr/attributions/assets/95868023/eb2a5265-712f-4b40-9480-5de54c24c413)
Attribution présente à ce jour.
