### ISSUE TITLE
Carte interactive Objectif paysages Ministère en charge de l’environnement

### ISSUE THREAD

**Issue by AdrienHegy** [osm-fr/attributions#312]
### Ce signalement concerne...

La carte interactive accessible ici : https://objectif-paysages.developpement-durable.gouv.fr/carte-interactive-1 n’affiche pas correctement les attributions.
- [ ] Sur ordinateur, l’attribution est masquée derrière la bande rouge permettant de sélectionner le territoire. 
- [ ] Sur mobile, elle est sous le footer.

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Informations supplémentaires

- Je n’ai pas effectué de prise de contact pour le moment.

**Comment by cquest** [comment]
Il faut prendre contact avec l'agence web qui a réalise le site (sous Drupal) et l'héberge... c'est dans les mentions légales.

**Comment by cquest** [comment]
Poke sur twitter: https://twitter.com/cq94/status/1669446223441326080

**Comment by AdrienHegy** [comment]
Réponse d’Ecedi sur le fil twitter le 21 juin.
Attributions correctes sur ordinateur et sur mobile (vérifié le 24 juin).
