### ISSUE TITLE
M Pulse (ville de Marseille)

### ISSUE THREAD

**Issue by nlehuby** [osm-fr/attributions#320]
### Ce signalement concerne…

Site web https://m-pulse.marseille.fr/map, [présenté au SOTM par la ville de Marseille](https://peertube.openstreetmap.fr/w/3iAfpGnP4PJeVvBedRXxnu)

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

Visiblement, ça serait un fond généré en interne par la ville de Marseille à l'aide de Géoserver. La seule attribution visible est "Ville de Marseille (TMS)"

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

Pas trouvé de lien de contact sur le site. Rien dans la vidéo du SOTM non plus

**Comment by Jean-BaptisteC** [comment]
L'attribution a été rajoutée
![image](https://github.com/osm-fr/attributions/assets/87148630/bff83f36-7698-44bd-a2b3-1e0ee30365be)
