### ISSUE TITLE
School-iti

### ISSUE THREAD

**Issue by lmagreault** [osm-fr/attributions#323]
### Ce signalement concerne…

Application SAAS School-iti de Okina (groupe Lumiplan)
Exemple : https://scolaire.transports.nouvelle-aquitaine.fr/school-iti/rna/#/school-iti/rna/traveller

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

Autre/inconnu (Thunderforest)

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsable contacté par Twitter le 30/07/2023 : 
https://twitter.com/lmagreault/status/1674822101176401933

**Comment by lmagreault** [comment]
Pris en compte par l'éditeur : https://twitter.com/LumiplanGroupe/status/1677256731838038016

**Comment by vinber** [comment]
salon tourisme, stand lumiplan, le nom de lumiplan me dit quelque chose ... et je viens de trouver :) et en  plus j'ai pu leur dire que cela avait été pris en compte, donc je ferme l'issue
