### ISSUE TITLE
Portails cartographiques Articque

### ISSUE THREAD

**Issue by flacombe** [osm-fr/attributions#340]
### Ce signalement concerne…

Les portails cartographiques web édités par la société Articque affichent un fond de carte provenant d'un serveur WMS propre à cette organisation.
Plusieurs éléments visibles sur les fonds de carte laissent penser que les données proviennent d'OSM et ont été simplifiées.

Par exemple sur celui-ci
https://demo-cdonline.articque.com/share/display/e1fd045d2ad665a94c01a3eca05b66451c0e941a

Et sur tous les exemples visibles en ligne
https://www.articque.com/nos-exemples/

![image](https://github.com/osm-fr/attributions/assets/5690599/81a188bf-5c36-4a56-879c-e9581b2458f2)
![image](https://github.com/osm-fr/attributions/assets/5690599/27e4c86a-ac2d-4900-9370-7475a6bfa837)

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

Autre/inconnu

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

Pas de contact pris pour l'instant, à suivre

**Comment by cquest** [comment]
Je confirme, je retrouve mes oeufs de pâques habituels.

**Comment by flacombe** [comment]
Mail envoyé à l'instant

> Madame, monsieur,
> 
> L'association OpenStreetMap France assure en France la promotion du projet de cartographie collaborative OpenStreetMap.
> Ce projet produit et assure la disponibilité d'un certain nombre de ressources constituées pour la plupart de manière bénévole.
> 
> Nous avons remarqué que certains de vos services cartographiques de fond de carte, notamment le serveur WMS accessible sur https://dalles.articque.com exposent des dalles produites à l'aide de données OpenStreetMap sans en mentionner la provenance.
> Nous souhaiterions que l'ensemble de vos logiciels, solutions et communications respectent les règles énoncées sur https://osm.org/copyright et les termes de la licence ODbL 1.0 s'il vous plaît.
> https://opendatacommons.org/licenses/odbl/1-0/
> 
> Cela prévoit notamment l'apposition d'une mention créditant le projet OpenStreetMap sur l'ensemble des contenus produits et éventuellement le repartage sous les termes de la licence ODbL 1.0 des données améliorées à partir de données OpenStreetMap (§4.4 de la licence).
> 
> Nous avons fait cette découverte à la suite de l'une de vos communications indiquant à juste titre l'intérêt de la cartographie dans le cadre d'activités économiques. Nous souhaiterions que le projet OpenStreetMap y soit associé, aux termes des règles prévues qu'il faut respecter pour préserver la motivation de ses contributeurs.
> 
> Vos équipes peuvent venir compléter le suivi de cette requête directement sur le ticket ouvert à cet effet.
> https://github.com/osm-fr/attributions/issues/340
> 
> Je me tiens à votre disposition pour envisager les solutions adaptées et constater la bonne prise en compte de notre demande.
> Bonne fin de semaine

**Comment by articque** [comment]
Bonjour @flacombe ,
Nous citons OpenStreetMap dans la rubrique "Licences" de notre logiciel (cf copie d'écran jointe). 
![OSM_1](https://github.com/osm-fr/attributions/assets/11867468/fadab2cb-9ece-4954-acb3-8bf1357f7b84)

Notre serveur de production contient bien une mention permanente de contribution OSM , comme vous pouvez le constater au lien suivant : https://www.articque.com/nos-exemples/atlas-ressources-humaines/

Merci de nous avoir signalé l'absence de citation sur notre serveur de démo, que nous allons mettre à jour dans un délai maximum de 60 jours.

Je note de vous informer dès que ce sera fait pour clôturer votre ticket.

Bonne semaine à votre équipe
Cordialement

**Comment by flacombe** [comment]
Bonjour @articque

Merci pour votre réponse !

C'est entendu pour votre production et les mentions dans les licences, dont nous confirmons la validité des mentions.
C'est en effet sur la démo que ça manquait et je ne m'étais pas aperçu de la différence.

Au plaisir, lorsque les quelques modifications nécessaires auront été mises en production.

**Comment by vdct** [comment]
> Notre serveur de production contient bien une mention permanente de contribution OSM

Plutôt qu'une simple mention il faudrait un **lien** vers la page https://www.openstreetmap.org/copyright 

![Capture d’écran de 2023-08-01 11-28-40](https://github.com/osm-fr/attributions/assets/2237260/fd5d69a4-3bae-4e39-bb2b-23ee1d8a6f76)
merci

**Comment by Jean-BaptisteC** [comment]
C'est corrigé sur les deux liens mentionnés dans le premier commentaire
![image](https://github.com/osm-fr/attributions/assets/87148630/8caa504c-a13b-4c04-987b-52cc355dcec8)

**Comment by articque** [comment]
Bonjour,

Toutes nos excuses pour cette confirmation tardive : la mention "OSM contributors" avec lien au clic vers https://www.openstreetmap.org/copyright a effectivement bien été ajoutée dans les délais en standard sur tous nos affichages cartographiques web, dès lors qu'ils utilisent des tuiles WMS Articque basées sur des données OSM.

Pouvons nous considérer que le ticket est prêt à être clôturé ?

Merci encore pour votre signalement, et au plaisir d'échanger avec vous à nouveau.

L'équipe Articque

**Comment by vinber** [comment]
> Pouvons nous considérer que le ticket est prêt à être clôturé ?

oui merci
