### ISSUE TITLE
garagiste-de-france.fr

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/attributions#349]
### Ce signalement concerne…

- https://garagiste-de-france.fr, annuaire (avec avis des clients) avec localisation via carte osm (cf pic.)

![Screenshot 2023-08-21 at 16-50-15](https://github.com/osm-fr/attributions/assets/36087963/8c8adc7e-4d22-413d-a8f8-2c1e2b8abdf7)

- "leaflet" (en B à D) renvoie vers le site de leaflet
- la page https://garagiste-de-france.fr/cgu.php donne le nom de l'éditeur du site 

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.fr

### Prise de contact

❌ Je ne l'ai pas contacté

**Comment by lefuturiste** [comment]
Dans le code 🤣 
```js
                L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
                    // Il est toujours bien de laisser le lien vers la source des données
                   // attribution: 'données © <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu <a href="//openstreetmap.fr">OSM France</a>',
                   ```

**Comment by lefuturiste** [comment]
Après investigation par l'utilisateur StC sur le chat télégram, il a déterminé que c'est un copié collé du tuto 
https://nouvelle-techno.fr/articles/pas-a-pas-inserer-une-carte-openstreetmap-sur-votre-site
Donc c'est un dev qui a commenté la ligne après le copié-collé pour une raison non déterminé.

**Comment by deuzeffe** [comment]
@lefuturiste merci pour les investigations ainsi qu'à StC.
Il s'avère que tous les <metiers|magasins>-de-france.fr présentent le même "défaut" et sont tous édités par le même éditeur... Peut-être qu'un des membres du CA pourrait prendre contact avec lui et lui signaler l'infraction à la licence.

**Comment by Jean-BaptisteC** [comment]
Le site semble indisponible a réessayer d'ici quelques mois.

**Comment by NathanBnm** [comment]
Le site est toujours indisponible. Je pense qu'on peut clôturer le ticket.
