### ISSUE TITLE
fetedelascience.fr/programme

### ISSUE THREAD

**Issue by tr19h9z5f6z63g5** [osm-fr/attributions#352]
### Ce signalement concerne…

https://www.fetedelascience.fr/programme, attendre que les items se chargent et cliquer sur la vue carte

Je vois bien le texte d'attribution dans le code source de la page, mais il ne s'affiche pas sur mon écran.

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

tile.jawg.io

### Prise de contact

❌ Je ne l'ai pas contacté

**Comment by benoit-dd** [comment]
à noter que l'attribution est correcte sur les mini-cartes des fiches individuelles des évènements ex:
https://www.fetedelascience.fr/illustrations-fantastiques-les-3d-decouvrir-decrypter-diffuser

**Comment by Jean-BaptisteC** [comment]
L'affichage est un peu buggé, mais si on scroll sur la page d'accueil, l'attribution est bien visible
