### ISSUE TITLE
situlearn.univ-lemans.fr/

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#360]
### Ce signalement concerne…

- [x] https://situlearn.univ-lemans.fr/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

Découverte sur https://mas.to/@imarfisi/111051927849145561

**Comment by vinber** [comment]
je peux voir pour le contact (j'ai commencé pour d'autres raisons un échange avec la cheffe de l'équipe de recherche). Mais je ne sais pas où cela se situe sur le site ?

**Comment by vinber** [comment]
merci, tu avais mis le pouet mais je n'avais pas bien regardé ... dans la doc de présentation pdf du site, il y a un extrait où les 2 sont présents donc je contacte pour divers sujets :)

**Comment by vinber** [comment]
prise de contact effectué, tempête professionnelle pendant 1 ou 2 semaines, reprise de contact en conséquence en suivant
