### ISSUE TITLE
cartographie.francetierslieux.fr/

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#361]
### Ce signalement concerne…

- [ ] https://cartographie.francetierslieux.fr/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

Autre/inconnu

### Prise de contact

❌ Je ne l'ai pas contacté

**Comment by vinber** [comment]
signalé sur le forum https://forum.tiers-lieux.org/t/manque-dattribution-openstreetmap-sur-la-cartographie-des-tiers-lieux/3926
