### ISSUE TITLE
La Confédération des buralistes

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#365]
### Ce signalement concerne…

- https://www.buralistes.fr/trouver-le-buraliste-pres-de-chez-vous

uniquement attribution Leaflet sur la carte

En revanche, attribution partielle dans les mentions légales (pas de lien):
https://www.buralistes.fr/mentions-legales

Réalisation par [insite](https://www.insite.coop/), qui utilisent pourtant un lien OSM pour indiquer leur localisation!

### Présence de l'attribution

⚠️ Attribution partielle

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsable contacté le : 18/10/2023
  - Responsable contacté par leur formulaire de support technique : https://www.insite.coop/support-technique
 
- Lié au signalement : #

**Comment by benoit-dd** [comment]
agence contactée

**Comment by Jean-BaptisteC** [comment]
Aucune carte n'est visible sur la page mentionnée
