### ISSUE TITLE
Mairie de Fresnes (94)

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/attributions#367]
### Ce signalement concerne…

- https://www.fresnes94.fr/
exemple : https://www.fresnes94.fr/association/fresnescyclette/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- contact via le formulaire du site https://www.fresnes94.fr/contactez-nous/

réalisation par #stratis

**Comment by Jean-BaptisteC** [comment]
Corrigée
![image](https://github.com/user-attachments/assets/959e0ab0-a5fa-44f3-919e-50e8d2548a47)
