### ISSUE TITLE
Terre de Jeux 2024

### ISSUE THREAD

**Issue by AdrienHegy** [osm-fr/attributions#377]
### Ce signalement concerne…

- [ ] Le site Terre de Jeux 2024 https://terredejeux.paris2024.org/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Comité d’organisation des jeux contacté par courrier le 17/10/2023

**Comment by Jean-BaptisteC** [comment]
Le site ne contient plus de carte seulement une page indiquant que le site est fermé, a voir pour ré ouvrir ce ticket pour les prochains JO
