### ISSUE TITLE
Syndicat mixte Ardèche Drôme Numerique (ADN)

### ISSUE THREAD

**Issue by pyrog** [osm-fr/attributions#38]
Page
- https://www.ardechedromenumerique.fr/eligibilite

Agence [Kyxar](https://www.kyxar.fr)

**Comment by Altonss** [comment]
Toujours aucune attribution au 03/01/2022

**Comment by flacombe** [comment]
C'est corrigé sur la page indiquée ci-dessus, je vous propose de fermer ce ticket

**Comment by cayenne17** [comment]
Je ferme le problème vu que c'est corrigé.

Il y a bien l'attribution `© OpenStreetMap contributors` et le lien pointe bien vers https://www.openstreetmap.org/copyright
![image](https://github.com/osm-fr/attributions/assets/47927025/de140159-ac04-4013-8f13-df73f83e0b7b)
