### ISSUE TITLE
choisirleservicepublic.gouv.fr

### ISSUE THREAD

**Issue by cquest** [osm-fr/attributions#381]
### Ce signalement concerne…

Site web https://choisirleservicepublic.gouv.fr/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsable contacté le : 
  - email envoyé le 18/102023 à assistance-candidat@choisirleservicepublic.gouv.fr (figure dans les mentions légales)

**Comment by Jean-BaptisteC** [comment]
Corrigée
![image](https://github.com/user-attachments/assets/63a4d317-0eb5-4a62-8b1c-691f97640221)
