### ISSUE TITLE
Annecy 2050 (Réinventons la ville)

### ISSUE THREAD

**Issue by jlgenet** [osm-fr/attributions#392]
### Ce signalement concerne…

Concertation participative de la ville d'Annecy
-  [x] [Annecy 2050 je participe](https://jeparticipe.annecy.fr/project/annecy-2050/collect/carte-participative)
- [ ] #393

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

Autre/inconnu

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Message à CAP Collectif contacté le : 6/11/23 
  - Responsable contacté par courriel à https://www.cap-collectif.com/contact (page contact)
- Lié au signalement : #

**Comment by vinber** [comment]
c'est ok maintenant

**Comment by vinber** [comment]
https://github.com/osm-fr/attributions/issues/395
