### ISSUE TITLE
jeparticipe.grandlyon.com/project/rive-droite/collect/boite-a-idees

### ISSUE THREAD

**Issue by AntoninDelFabbro** [osm-fr/attributions#394]
### Ce signalement concerne…

- [ ] https://jeparticipe.grandlyon.com/project/rive-droite/collect/boite-a-idees

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

Autre/inconnu

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

- Lié au signalement : #393

**Comment by vinber** [comment]
l'attribution est présente maintenant, ils ont du faire la même mise à jour que pour https://github.com/osm-fr/attributions/issues/395
