### ISSUE TITLE
Un template pour le manque d'attribution

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#4]
pour la constitution d'un template, les éléments à faire apparaitre et n'hésitez pas à répondre

- renseigner le site web et le type de manque (juste la mention, l'absence de lien url vers /copyright, peut-être des labels ?)
- préciser si un contact a été pris ou pas, par quel moyen,
- éventuellement une capture d'écran ?

tout ce qui est date, qui est réglé de fait par github donc sans doute inutile.

Peut-être renseigner si la personne qui fait l'issue est l'auteure de la prise de contact ou pas ?

**Comment by cquest** [comment]
Tu est maintenant mainteneur du dépôt, tu peux créer le template.

J'ai aussi créé 3 labels:
- attribution manquante (totalement)
- attribution visible après interaction
- attribution sans lien vers osm.org/copyright

**Comment by vinber** [comment]
super merci

**Comment by vinber** [comment]
Comment fait on pour les labels ? je n'ai pas la main dessus si ?
J'ajouterai bien un label Signalé ou truc plus détaillé pour dire que l'information a bien été transmise au site, à la structure concernée

**Comment by vinber** [comment]
@cquest je ne vois pas Settings comme ils semblent le dire ici https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by jocelynj** [comment]
@vinber : Tu as dû recevoir un email pour activer ton accès mainteneur à ce repository. J'ai `Awaiting vinber’s response` pour ton accès.

**Comment by vinber** [comment]
:D je ne l'ai pas vu passer mais je viens de trouver, j'ai validé ! merci beaucoup à tous les 2

**Comment by vinber** [comment]
mais toujours pas la possibilité de voir le Set up templates under issues, le point 3 https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by vinber** [comment]
@AntoninCurtit as-tu déja réalisé des templates ? car ton readme est parfait, cela serait encore mieux comme template non ?
Moi je ne trouve pas comment faire :(

**Comment by AntoninCurtit** [comment]
Ça serait mieux d'avoir un template je suis totalement d'accord, et merci ! ;)
Il faut avoir des droits sur le repo – ce que je n'ai pas – mais [la doc](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) pourrait t'aider ! 👍

**Comment by vinber** [comment]
oui mais c'est mon problème c'est que j'ai bien settings mais pas la partie sur les issues et le set up template. Je le trouve bien sur d'autres dépots.

Je ne peux donc pas le faire non plus @jocelynj @cquest

**Comment by jocelynj** [comment]
@vinber : je t'ai passé Admin sur ce repository.

**Comment by vinber** [comment]
merci, premier essai https://github.com/osm-fr/attributions/issues/new/choose

**Comment by Altonss** [comment]
Je vais fermer cette issue, comme maintenant les discussion autour de la template sont dans #137 :)
Mais vous pouvez le rouvrir à tout moment :)
