### ISSUE TITLE
Carte interactive du SYMADREM - risques crues delta du Rhône

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#401]
### Ce signalement concerne…

- (https://cartographie.symadrem.fr/)
- fond cartodb

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

CartoDB

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

Signalement fait sur le forum

- https://forum.openstreetmap.fr/t/carte-interactive-du-symadrem-risques-crues-delta-du-rhone/19405/1

aucune idée pour le contact avec le syndicat

**Comment by Jean-BaptisteC** [comment]
email de contact: symadrem@symadrem.fr trouvé dans les mentions légales

**Comment by cayenne17** [comment]
@vinber, @Jean-BaptisteC Je viens de vérifier, il y a une attribution en bas à gauche
![image](https://github.com/osm-fr/attributions/assets/47927025/1ecbad64-823d-4e00-a6e1-c86564ad1dac)

il peut-être fermé ?

**Comment by vinber** [comment]
@cayenne17 je t'ai donné la main pour que tu puisses fermer des issues  :)

**Comment by vinber** [comment]
merci du ping !

**Comment by cayenne17** [comment]
@vinber J'ai vu, merci
