### ISSUE TITLE
Manque d'attribution Open Archives SNCF

### ISSUE THREAD

**Issue by Kalepom** [osm-fr/attributions#407]
### Ce signalement concerne…

- La [carte des ressources Open Archives](https://openarchives.sncf.com/recherche_map) de la SNCF n'a pas d'attribution, ou très partielles

### Présence de l'attribution

⚠️ Attribution partielle

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsable contacté le : 13/12/2023
  - Responsable contacté par : email open-data@sncf.fr
- Lié au signalement : #

**Comment by vinber** [comment]
merci, et le certificat est expiré le 14/12, cela sent le site à jour :)

**Comment by NathanBnm** [comment]
Il semble qu'il n'y ait plus de carte sur le site

**Comment by vinber** [comment]
alors on ferme, cela fait du bien :)
