### ISSUE TITLE
[Business Geografic – Ciril Group]

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#42]
✅ J'ai noté un usage très important d'OSM par cet éditeur ainsi que de la bonne volonté pour corriger, rapidement, le tout de manière très pro, très agréable.

- 16/07/2020 (email)
  - [x] https://geo.grand-lac.fr/adws/app/dde324fc-5a13-11e9-9b37-9b6a94bbfbee/index.html?context=mxZY

- 17/07/2020 (email)
  - [x] https://www.cdc-oleron.com/acces-rapides/carte-interactive/
  - [x] https://carto-tempete-alex.departement06.fr/infos_chantiers_en_temps_r_el/index.html
  - [x] https://sports.mairie-saintnazaire.fr/#/
    - C'est à la commune de Saint-Nazaire de rentrer dans les clous. #43
  - > J’ai également fait un petit article dans notre FAQ pour aiguiller les clients sur le bon usage des flux OSM

- 21/10/2020 (email)
  - [x] https://geo.vincennes.fr/adws/app/9604f026-5f23-11e8-a07b-55dfecc66070/index.html
  - > nous avons demandé à nos clients utilisant le flux OSM de remplir manuellement les données de copyright pour que toutes les cartes GEO soient progressivement en conformité avec les conditions d’utilisation de la donnée OSM.

- 20/12/2020 (email)
  - [x] https://www.cirilgroup.com/fr/contact.html

- 28/07/2021 (email)
  - [x] https://geo.valenceromansagglo.fr/adws/app/f3385c4b-e128-11ea-a01e-c5082cb6108a/
    - Réponse le 28/07/2021 – Information transmise au client concerné. 

- 24/10/2021 (twitter)
  - [x] https://sig.coeuressonne.fr/adws/app/8117b2f4-61a6-11e9-9860-1943df920d4c/
  - [x] http://geoservices.business-geografic.com/adws/app/1bb265a1-84b2-11e6-87d9-e30ca67bce95/index.html
  - [x] https://map.ccibaseco-normandie.fr/adws/app/6488468d-4f19-11e9-87b0-65f91e19811b/index.html
  - [x] https://geoweb.valdemarne.fr/adws/app/33ae0c21-648e-11eb-a18a-f13ce2e0a4f2/
  - [x] https://webcarto.agglo-accm.fr/adws/app/f3610db8-acfc-11e8-9f58-572c9b4dd220/index.html
  - [x] https://www.geoloire42.fr/adws/app/988f7e2c-0b2b-11e8-8971-a3c4f9ed35c1/index.html
  - [x] https://sigeo23.creuse.fr/sante/index.html
  - [x] https://geo.gpsea.fr/adws/app/6dea99ff-837e-11e9-af9e-dd2dac346373/?context=VqWc
  - [x] https://cartes.observatoire-eau-martinique.fr/sig_eau_martinique/
  - [x] http://www4.observatoiredesfragilites.fr/adws/app/90704e4e-5f67-11e9-a532-557eda8979c9/?_ga=2.65808878.1127854441.1627292429-1135366577.1611052585
  - [x] https://sig.grandcalais.fr/adws/app/74bc2e8e-2a97-11eb-9dab-8bd7ce30f797/ (Positron = CartoDB = OSM)
  - [x] https://www.cedejcapmas.org/adws/app/4d5b52dc-669d-11e9-b6a6-975656a88994/

**Comment by Altonss** [comment]
> Une de plus
> 
>     * [ ]  https://sig.coeuressonne.fr/adws/app/8117b2f4-61a6-11e9-9860-1943df920d4c/
> 
> 
> Combien de fois faudra-t-il rappeler à cette agence qu'elle a encore "oublié" l'attribution OSM mais pas la sienne. C'est quasi systématique, non ?

Celle-ci a été corrigée, ce serait bien de cocher la case, comme ça on voit ce qui reste à faire ^^

**Comment by Altonss** [comment]
Tout semble corrigé à présent, merci beaucoup!!

**Comment by fnicollet** [comment]
Parfait :). Pour information, nous avons réalisé une amélioration de notre logiciel pour ajouter automatiquement les copyrights s'ils proviennent de certaines URL. Les clients Business Geografic migrent petit à petit vers cette nouvelle version, donc il devrait y avoir de moins en moins de souci
