### ISSUE TITLE
Very Important Parking

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#420]
### Ce signalement concerne…

- [ ] Applications VIP (Very Important Parking) https://very-important-parking.fr/, dont les places de parking PMR proviennent majoritairement d'OSM.

Données OSM extraites avec les tags amenity=parking_space + parking_space=disabled, localisation identique, exhaustivité correspondant à ces tags.
Les informations sur les commerces ne semble pas provenir d'OSM (localisation différente).

### Présence de l'attribution

❌ Pas d'attribution

### Vérifications

Données vérifiées sur :
- Pontarlier
- Saint-Maur-des-Fossés
- Auxerre
- 
### (Facultatif) Quel est le fond de carte ?

Fond de carte de l'OS du smartphone.

### Prise de contact

✔️ Je l'ai contacté
- via message sur le compte Facebook (22/01/2024)
- via retour dans l'appli elle-même (22/01/2024)

### Informations supplémentaires

- Responsable contacté le : 22/01/2024
  - Responsable contacté par (courriel, Twitter…) : Facebook Messenger

**Comment by cquest** [comment]
J'ai complété, tentative de prise de contact aussi de mon côté et vérification pour les données à plusieurs endroits.

**Comment by cquest** [comment]
L'attribution est désormais bien présente sur l'app et le site web et une collaboration s'engage.
