### ISSUE TITLE
annuaire-des-restaurants.fr

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#433]
### Ce signalement concerne…

- [ ] https://annuaire-des-restaurants.fr/avis/restaurants/kevser-kebab-28926.html

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.fr

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

- Responsable contacté le : 
  - Responsable contacté par (courriel, Twitter…) : 
- Lié au signalement : #

**Comment by Jean-BaptisteC** [comment]
Le backend du site ne semble pas être fonctionnel

**Comment by Jean-BaptisteC** [comment]
L'affichage du site web fonctionne, mais la recherche de restaurant ne fonctionne pas

**Comment by NathanBnm** [comment]
Le site n'est plus disponible y'a une page russe à la place
