### ISSUE TITLE
https://www.valgourmand.com

### ISSUE THREAD

**Issue by pyrog** [osm-fr/attributions#44]
Page d'accueil en cliquant sur [OÙ NOUS TROUVER](https://www.valgourmand.com)

Agence [Kyxar](https://www.kyxar.fr)

**Comment by vinber** [comment]
Salut, dans la série d'issue, je ne sais pas si tu as pris contact ou pas. Peut être un label à créer du type 'prendre contact'

**Comment by pyrog** [comment]
Pas de contact, c'est pour ça que j'avais suggéré de créé cette étiquette et de revoir les modèles 😉
