### ISSUE TITLE
prepare.paris2024.org

### ISSUE THREAD

**Issue by cquest** [osm-fr/attributions#443]
### Ce signalement concerne…

Pas d'attribution sur https://prepare.paris2024.org/search/

### Présence de l'attribution

❌ Pas d'attribution

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

Mail envoyé à cpj@paris2024.org le 5/6/2024
---
Bonjour,

Nous sommes heureux de constater sur le site https://prepare.paris2024.org/search/ utilise un fond de carte provenant de données OpenStreetMap.

Cependant, nous vous rappelons qu'il est obligatoire de mentionner de façon clairement visible l'origine du fond de carte, comme expliqué sur https://www.openstreetmap.org/copyright

Ce n'est pas le seul site paris2024 où cette attribution obligatoire est manquante, deux autres ont déjà fait l'objet de signalements:

- https://github.com/osm-fr/attributions/issues/287 (octobre 2023)

- https://github.com/osm-fr/attributions/issues/377 (mars 2023)

Merci de faire le nécessaire dans les meilleurs délais.

**Comment by cquest** [comment]
Voir aussi https://github.com/osm-fr/attributions/issues/287 et https://github.com/osm-fr/attributions/issues/377

**Comment by cquest** [comment]
Message aussi envoyé sur https://support.olympics.com/hc/fr/requests/new

**Comment by Jean-BaptisteC** [comment]
Le site ne contient plus de carte seulement une page indiquant que le site est fermée, avoir pour ré ouvrir ce ticket pour les prochains JO
