### ISSUE TITLE
Owaka live

### ISSUE THREAD

**Issue by pyrog** [osm-fr/attributions#448]
### Ce signalement concerne…

- [ ] https://owaka.live

### Présence de l'attribution

❌ Pas d'attribution (elle existe mais semble totalement cachée par le bandeau en bas de l'écran)

### Quel est le fond de carte ?

openstreetmap.org
maptiler.com (couches Terrain et Satellite)

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsable contacté le : 17/06/2024
  - Responsable contacté par courriel : hello@owaka.com

**Comment by Jean-BaptisteC** [comment]
Présent à gauche du fond de plan
![image](https://github.com/user-attachments/assets/ee981797-0263-484c-b598-33cd1770be66)

**Comment by pyrog** [comment]
Je n'ai pas fait de copie d'écran donc je ne sais pas si je n'ai pas vu l'attribution ou si elle a été rajoutée depuis.
En tout cas je n'ai pas reçu de mél.

**Comment by Jean-BaptisteC** [comment]
Ok Merci pour ton retour
Je ferme le ticket
