### ISSUE TITLE
bateaux.com

### ISSUE THREAD

**Issue by atchisson** [osm-fr/attributions#451]
### Ce signalement concerne…

- [ ] [le guide marine des ports de bateaux.com](https://www.bateaux.com/plaisance/port/camaret-mer-REFY5SUmE49X4s,/1/guide-marine)

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsable contacté le : 28 juin 2024
  - Responsable contacté par (courriel, Twitter…) : [formulaire sur leur site ](https://www.bateaux.com/contact/redaction)

**Comment by Jean-BaptisteC** [comment]
Corrigé
![image](https://github.com/user-attachments/assets/d5ecfc1c-64a2-4ea3-b036-18b0c11cd6df)
