### ISSUE TITLE
https://sites-vauban.org

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#452]
### Ce signalement concerne…

[Réseau des sites majeurs de Vauban](https://sites-vauban.org)

réalisé par l'agence https://www.digitaledeluxe.fr/

attribution présente sur la page générales des sites: https://sites-vauban.org/ressources/les-fortifications-de-vauban-en-france

absente sur les pages individuelles : ex https://sites-vauban.org/ressources/site-vauban/toul#

### Présence de l'attribution

❌ Pas d'attribution

### Prise de contact

✔️ Je l'ai contacté

### Informations supplémentaires

- Responsable contacté le : 30/06/2024
  - Responsable contacté par formulaire de contact: https://sites-vauban.org/contact
  -

**Comment by atchisson** [comment]
ça a l'air corrigé, même un peu trop ! 
![image](https://github.com/osm-fr/attributions/assets/41149397/cf1d432c-f34f-4720-b139-37e07d6759a7)
