### ISSUE TITLE
Office de tourisme https://www.coeurdebastides.com/fr/

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#464]
### Ce signalement concerne…

site de l'Office de Tourisme Cœur de Bastides (Lot)
https://www.coeurdebastides.com/fr/

petite carte OSM sur les fiches des commerces, lieux etc.

https://www.coeurdebastides.com/fr/fiche/739/le-salon-de-valerie
https://www.coeurdebastides.com/fr/fiche/86/parranquet-un-village-dans-la-vallee-du-dropt

réalisation par 
HEURISKO
23 avenue du Mirail – Parc du Mirail
33370 Artigues-près-Bordeaux
[www.heurisko.fr](https://www.heurisko.fr/)

### Présence de l'attribution

❌ Pas d'attribution

### Informations supplémentaires

- Responsable contacté le : 25/07/2024
- office de tourisme contacté par courriel : https://www.coeurdebastides.com/

**Comment by heurisko** [comment]
Bonjour, pouvez vous vérifier que le nécessaire a bien été fait svp ?

**Comment by Jean-BaptisteC** [comment]
Corrigé, je ferme le ticket
