### ISSUE TITLE
Paris 2024 GPS Accred

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/attributions#465]
### Ce signalement concerne…

- https://play.google.com/store/apps/details?id=com.benomad.benavjo
Semble utiliser Mapbox

### Présence de l'attribution

❌ Pas d'attribution

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

- Responsable contacté le : 
  - Responsable contacté par (courriel, Twitter…) : 
- Lié au signalement : #

**Comment by NathanBnm** [comment]
L'application n'est plus disponible je pense qu'on peut fermer
