### ISSUE TITLE
Hopital saclay tout neuf 

### ISSUE THREAD

**Issue by tykayn** [osm-fr/attributions#478]
### Ce signalement concerne…

- [ ] la carte du site web https://www.gh-nord-essonne.fr/site-hospitalier/hopital-paris-saclay
attribution juste mentionnant "leaflet"

### Présence de l'attribution

❌ Pas d'attribution

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

- Responsable contacté le : 
  - Responsable contacté par (courriel, Twitter…) : 
- Lié au signalement : #

**Comment by Jean-BaptisteC** [comment]
Doublon du #477
