### ISSUE TITLE
Toulouse tourisme

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/attributions#481]
### Ce signalement concerne…

- https://www.toulouse-tourisme.com/sortir-a-toulouse/lunexplorer-cite-de-lespace/

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

- Responsable contacté le : 
  - Responsable contacté par (courriel, Twitter…) : 
- Lié au signalement : #

**Comment by NathanBnm** [comment]
Contacté via contact@toulouseatout.com le 02/10/2024

**Comment by NathanBnm** [comment]
Réponse reçue le 10/10/2024 :

> Bonjour Monsieur,
> 
> Suite à votre remarque, nous avons fait le nécessaire pour afficher le crédit sur les cartes affichées sur notre site.
> 
> Cordialement

Ils ont ajouté l'attribution suivante : 
<img width="255" alt="Capture d’écran 2024-10-10 à 15 32 05" src="https://github.com/user-attachments/assets/1cfead5e-e253-4778-ab66-273ff58dcaba">
