### ISSUE TITLE
ma sécurité

### ISSUE THREAD

**Issue by vinber** [osm-fr/attributions#506]
### Ce signalement concerne…

- https://www.masecurite.interieur.gouv.fr/fr/trouver-un-commissariat-une-gendarmerie

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

❌ Je ne l'ai pas contacté

**Comment by Jean-BaptisteC** [comment]
Page de contact
https://www.masecurite.interieur.gouv.fr/fr/signalez-un-dysfonctionnement-technique

**Comment by Jean-BaptisteC** [comment]
Le site a été signalé à la fondation
https://github.com/openstreetmap/tile-attribution/issues/76

**Comment by vinber** [comment]
envoyé un mot rappelant les 2 issues

**Comment by Jean-BaptisteC** [comment]
Corrigé sur desktop et mobile
