### ISSUE TITLE
defibrillateurs.info

### ISSUE THREAD

**Issue by lefuturiste** [osm-fr/attributions#515]
### Ce signalement concerne…

- https://www.defibrillateurs.info/

Site édité par [AFPAIC](https://www.afpaic.fr/) 

### Présence de l'attribution

❌ Pas d'attribution

### (Facultatif) Quel est le fond de carte ?

openstreetmap.org

### Prise de contact

❌ Je ne l'ai pas contacté

### Informations supplémentaires

- Responsable contacté le : 
  - Responsable contacté par (courriel, Twitter…) : 
- Lié au signalement : #

**Comment by Jean-BaptisteC** [comment]
Doublon de #400
