### ISSUE TITLE
LCL

### ISSUE THREAD

**Issue by rbeuque74** [osm-fr/attributions#58]
LCL – Pas d'attribution

**Description**

- Page de localisation des agences bancaires
- https://www.lcl.fr/agence-banque/00804-LCL-PARIS-ODEON
- Pas de prise de contact

**Comment by AntoninCurtit** [comment]
Sauf erreur de ma part, les tuiles sont de Here Maps (https://1.base.maps.api.here.com/maptile/2.1/maptile/newest/normal.day/15/16596/11273/512/png8?app_id=wuwcfodw24wEgfuId2ME&app_code=86krut5Lm2bRstOLVB2MSg&ppi=320) – bien que ressemblant très fortement à OSM et fonctionnant couramment avec Leaflet.

Issue à clore, merci du signalement ! 😉

**Comment by rbeuque74** [comment]
Bien vu, my bad, je clos l'issue.
