### ISSUE TITLE
[Agence IRIS Interactive]

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#61]
⚠️ Agence non contactée

- [ ] https://www.destinationlouelison.com/organiser/balades-et-randonnees/randonnees-equestres/
- [ ] https://www.damgan-larochebernard-tourisme.com/preparer-son-sejour/restaurants/

Et sûrement d'autres...

**Comment by vinber** [comment]
report dans #28 car doublon pour l'agence du #28
