### ISSUE TITLE
GTJ (Grandes Traversées du Jura)

### ISSUE THREAD

**Issue by pyrog** [osm-fr/attributions#65]
### Pas d'attribution
<img width="76" alt="Leaflet" src="https://user-images.githubusercontent.com/2158081/129334453-8147ba84-cc7b-4946-be70-e80fbf60a2ae.png">

- https://www.gtj.asso.fr/contact/
- https://www.gtj.asso.fr/meteo-ete/

### Double attributions
<img width="579" alt="Double attribution" src="https://user-images.githubusercontent.com/2158081/129334241-96511141-f320-45b3-8603-c3c7170eaec9.png">

- https://www.gtj.asso.fr/itineraires-et-activites/gtj-a-pied/
- https://www.gtj.asso.fr/itineraires-et-activites/gtj-a-vtt/
- https://www.gtj.asso.fr/itineraires-et-activites/gtj-a-velo/
- https://www.gtj.asso.fr/itineraires-et-activites/gtj-a-cheval/
- https://www.gtj.asso.fr/itineraires-et-activites/gtj-a-ski-de-fond/
- https://www.gtj.asso.fr/itineraires-et-activites/gtj-a-raquette/
- https://www.gtj.asso.fr/itineraires-et-activites/gtj-a-ski-de-randonnee-nordique/
- https://www.gtj.asso.fr/hebergements-et-restauration/?sfid=231&_sft_hebergement_categories=a-ski-de-randonnee-nordique

### Orthographe des noms
Il n'y a pas d'espaces dans les noms OpenCycleMap et OpenStreetMap.
<img width="232" alt="Open Street Map" src="https://user-images.githubusercontent.com/2158081/129332609-eb79087e-631e-4ab5-ac92-92cad33dffef.png">

### Contact
Par téléphone et par mél le 13/08/2021. Le responsable rentre de vacances le 1/09/2021.

**Comment by Altonss** [comment]
Les deux problèmes de non-attribution ont été résolus!
Je pense qu'on peut donc fermer cette issue (comme les deux autres soucis mentionnés sont plutôt anecdotiques :)
