### ISSUE TITLE
Ville de Vanves, pas d'attribution

### ISSUE THREAD

**Issue by bmallet** [osm-fr/attributions#68]
**Description**
- https://www.vanves.fr/ma-ville/ma-mairie/services-municipaux-261.html
- courriel envoyé le 15/01/2021 à webmaster@ville-vanves.fr

Conception et réalisation : Stratis

**Comment by AntoninCurtit** [comment]
Duplicate of #27

**Comment by Altonss** [comment]
Aucune nouvelle depuis?

**Comment by AntoninCurtit** [comment]
C'est qu'il faut contacter l'agence pour tout un panel de sites, je ne crois pas qu'aucun de nous l'ai fait

**Comment by Altonss** [comment]
Ah d'accord :)
Parce dans la description il était marqué:
> courriel envoyé le 15/01/2021 à [webmaster@ville-vanves.fr](mailto:webmaster@ville-vanves.fr)

**Comment by AntoninCurtit** [comment]
Oups, j'ai sauté ce passage, _décidément_...

**Comment by Altonss** [comment]
D'après ce que je vois, l'attribution est encore après interaction

**Comment by Jean-BaptisteC** [comment]
C'est corrigé
![image](https://github.com/user-attachments/assets/e5155abc-5349-42cc-8748-6792489605a3)
