### ISSUE TITLE
[Agence Stratis] plusieurs sites sans attribution

### ISSUE THREAD

**Issue by bmallet** [osm-fr/attributions#69]
**Description**
- web agency Stratis : https://www.stratis.fr
- [ ] réalise de nombreux sites pour collectivités (exemple Ville de Vanves / https://www.vanves.fr/ma-ville/ma-mairie/services-municipaux-261.html) et semble quasi systématique que l'utilisation d'OSM se fait toujours sans attribution
- test avec première référence (parmi https://www.stratis.fr/agence-web-secteur-public/clients?tx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D=179&cHash=f6c15048b1f292fd59ad908e65889b8d) : Petit-Quevilly...
- [ ] ... et toc pas d'attribution sur https://www.petit-quevilly.fr/decouvrir-la-ville/la-ville/plan-de-la-ville

- Courriel envoyé à contact@stratis.fr le 19/08/21

**Comment by AntoninCurtit** [comment]
Duplicate of #27

**Comment by vinber** [comment]
je propose de garder https://github.com/osm-fr/attributions/issues/27 et fermer ici
