### ISSUE TITLE
À suivre – geonarra.com

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#7]
- [ ] Concerne https://www.geonarra.com/
- Site hors-ligne pour l'heure (provisoirement ?)
- Contacté le [26 juin 2020](https://twitter.com/OSM_Pontarlier/status/1276522989677350913)
  - Pas de réponse
- Contacté par email le 14/04/21
  - Pas de réponse

**Comment by Altonss** [comment]
Je vais fermer cette issue pour le moment, car l'url ne fonctionne pas.
