### ISSUE TITLE
APHP, pas d'attribution

### ISSUE THREAD

**Issue by bmallet** [osm-fr/attributions#70]
**Description**
- https://aphp.fr/hopitaux
- courriel tenté mais adresse non disponible sur le site
- https://twitter.com/bmallet/status/1428422700209512448
- et formulaire de contact vers la webagency concerné : https://www.adimeo.com/contact

**Comment by bmallet** [comment]
Retour rapide de la web agency (Adimeo) :
_Le 20/08/2021 à 09:01, Marine Soroko a écrit :_
> Votre remarque au sujet d’OpenStreetMap est bien reçue et légitime !
> J’en fais part de ce pas aux équipes projet pour que la mention soit 
> mise en place rapidement.

**Comment by cquest** [comment]
Masquage volontaire trouvé dans https://www.aphp.fr/sites/all/modules/custom/aphp_carto/css/aphp_carto.css

Contact établi via le forum.

**Comment by Altonss** [comment]
Sur https://aphp.fr/hopitaux l'attributon est maintenant correcte.
