### ISSUE TITLE
Campus Condorcet Aubervilliers

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/attributions#71]
Campus Condorcet Aubervilliers – Pas d'attribution OSM
**Description**
https://www.campus-condorcet.fr/cartographie

seulement attribution Leflet

prise de contact le 24/08/2021 par leur formulaire de contact

à voir si la source du problème ne vient pas de leur outil de gestion https://www.ksup.org/ 
et/ou de 
Équipe Kosmos -B 419 223 425. 8 rue Kervégan | 44000 Nantes

**Comment by benoit-dd** [comment]
à noter que sur les fiches individuelles des bâtiments, l'attribution ©OpenStreetMap est bien présente
![image](https://user-images.githubusercontent.com/52233014/148568229-28235aee-7b6a-4c4d-8dc1-ca656220316f.png)

https://www.campus-condorcet.fr/fr/plan/residence-etudiante-condorcet-omega

**Comment by benoit-dd** [comment]
réponse par mail de K-Sup, correction prévue dans leur prochaine mise à jour, ils devraient venir l'annoncer ici une fois fait.

**Comment by benoit-dd** [comment]
réponse aujourd'hui de l'université qui a aussi fait remonter la demande au presta

**Comment by Jean-BaptisteC** [comment]
Le problème est corrigé
