### ISSUE TITLE
Liveli - manque d'attribution

### ISSUE THREAD

**Issue by Kalepom** [osm-fr/attributions#73]
https://www.liveli.fr/creches/marsac-sur-l-isle/
Attribution correcte sur la carte générale des crèches, mais manque des attributions sur les fiches des crèches.
Envoi d'un mail le 26/08/21 à privacy.hq.cat@sodexo.com (en contact dans les Mentions légales)

**Comment by Altonss** [comment]
Des nouvelles depuis? Rien a changé sur leur site

**Comment by Kalepom** [comment]
Non, je n'ai pas eu de retour à mon mail.
________________________________
De : Altonss ***@***.***>
Envoyé : jeudi 7 avril 2022 00:38
À : osm-fr/attributions ***@***.***>
Cc : Lucas ***@***.***>; Author ***@***.***>
Objet : Re: [osm-fr/attributions] Liveli - manque d'attribution (#73)


Des nouvelles depuis? Rien a changé sur leur site

**Comment by Kalepom** [comment]
On a du les vexer, il sont passés sur un fond de carte Google Maps :/
