### ISSUE TITLE
Site de la ville de Vézelin-sur-Loire (42) - Pas d'attribution

### ISSUE THREAD

**Issue by pl6025** [osm-fr/attributions#76]
Site de la ville de Vézelin-sur-Loire (42) - Pas d'attribution
...

- http://www.vezelin-sur-loire.fr/ (carte incrustée en bas de toutes les pages)
- Créateur du site web : Syndicat Intercommunal A.GE.D.I. (Siège social : Mairie de DHUISY – 77440 DHUISY)
- 07/09/2021, courriel envoyé à mairie@vezelin-sur-loire.fr

**Comment by lefuturiste** [comment]
Le problème semble corrigé (vérifié aujourd'hui)

**Comment by Altonss** [comment]
Je vais donc fermer pour l'instant (je n'ai trouvé aucune autre carte à part celle de la page d'accueil qui est effectivement bien attribuée), merci!
