### ISSUE TITLE
[Agence SQLI]

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#8]
# Site de l'agence
- [x] **Corrigé** en ce 14/04/2021.
Sollicité en nov. 2020 pour https://www.sqli.com/Accueil/Groupe/Agences/Aston-Ecole-Arcueil, résolu après plusieurs relances.

**Comment by Altonss** [comment]
On peut donc fermer cette issue @AntoninCurtit ?

**Comment by AntoninCurtit** [comment]
Terriblement aux aguets de tout ce qui se passe ici, ce @Altonss... ;)

Justement, je me faisait la remarque que non, peut-être faudrait-il laisser les issues des agences ouvertes. Histoire de retrouver facilement cet "historique" des agences, et éviter de recréer plusieurs issues [Agence SQLI].

Mais je suis divisé, alors... Comme tu le sens ! Faut trancher, je suis mauvais pour ça.

**Comment by Altonss** [comment]
> Justement, je me faisait la remarque que non, peut-être faudrait-il laisser les issues des agences ouvertes. Histoire de retrouver facilement cet "historique" des agences, et éviter de recréer plusieurs issues [Agence SQLI].
> 
> Mais je suis divisé, alors... Comme tu le sens ! Faut trancher, je suis mauvais pour ça.

Je dirais qu'on laisse l'issue de l'agence ouverte tant qu'on a des sites qui ne sont pas corrigés, ce qui n'est pas le cas en ce moment il me semble, non?

**Comment by AntoninCurtit** [comment]
Exact, mais je me disais que quand dans X jours il va nous tomber un site de cette agence, après l'issue fermée, et bien peut-être que quelqu'un irai recréer une issue [Agence SQLI].

- Risque de doublon
  - Au pire, on mes des # dans les issues en double pour les lier
- Est une étape dans plus dans https://github.com/osm-fr/attributions/issues pour retrouver l'agence, qui impliquera de chercher aussi dans les issues fermées / supprimer le texte `is:open`.

C'était mes petites "frustrations" et gênes à l'idée de fermer, c'est tout. :)

**Comment by Altonss** [comment]
Ah oui effectivement, je comprends! Après je trouve ça bien de faire le "ménage" aussi, dans le sens où quand on a plus aucun site avec un souci pour une certaine agence, il n'y a pas trop d'intérêt à la garder ouverte. Dans l'idéal il faudrait voir le nombre d'issue tendre vers 0, cela voudrais dire que les problèmes d'attribution sont résolus :)

**Comment by AntoninCurtit** [comment]
D'ailleurs, pour le label Marquage, je crois que ça ne s'applique pas dans ce cas-là car ce sont des tuiles .org et pas .fr — voir https://twitter.com/osm_fr/status/1420285591598649356

---

Ça se tient ! :)

**Comment by Altonss** [comment]
> D'ailleurs, pour le label Marquage, je crois que ça ne s'applique pas dans ce cas-là car ce sont des tuiles .org et pas .fr — voir https://twitter.com/osm_fr/status/1420285591598649356

Ah j'avais mal compris, il faudrait ajouter cela dans la description du label :)
