### ISSUE TITLE
Groupe Up (Chèque Déjeuner)

### ISSUE THREAD

**Issue by bmallet** [osm-fr/attributions#87]
Sur page de recherche : https://ou-cheque-dejeuner.fr/recherche
Message laissé via formulaire de contact (https://groupe.up.coop/fr/contact)

**Comment by Altonss** [comment]
J'ai l'impression que les tuiles utilisées proviennent de HERE

**Comment by vinber** [comment]
je ne trouve même pas la carte :(

**Comment by Altonss** [comment]
> je ne trouve même pas la carte :(

Il faut sélectionner un moyen de paiement, puis taper un code postal par exemple, et ensuite cliquer sur carte dans les résultats

**Comment by vinber** [comment]
ok merci !
je confirme que c'est here, donc je pense que l'on peut fermer l'issue

je t'ai changé de rôle pour que tu puisses fermer des issues
