### ISSUE TITLE
À vérifier – oscaro.com

### ISSUE THREAD

**Issue by AntoninCurtit** [osm-fr/attributions#9]
- Sollicité par email le 16/12/2020
  - Pas de réponse
- Contacté par [Twitter](https://twitter.com/OSM_Pontarlier/status/1357658872194998273) le 05/02/2021
  - Le jour-même, réponse de 2 employés en privé, qui m'ont assuré une mise à jour au plus vite/la semaine suivante.

- [ ] À vérifier.

**Comment by maddingue** [comment]
Bonjour,

Je suis l'un des deux employés d'Oscaro qui avaient répondu en privé.

Désolé, on avait en effet oublié de vous répondre par la suite, parce que cela avait pris plus de temps que prévu. On utilisait un service déployé en interne, mais suite à des problèmes pour le mettre à jour afin d'être en conformité, on est finalement passé sur un service externe, Maptiler. Celui-ci contient bien l'attribution à OpenStreetMap. J'ai fait un petit test tout à l'heure pour vérifier, et on peut voir les attributions en bas à droite, même si cela pourrait être mieux cadré (mais c'est peut-être lié à mon navigateur) : 
![image](https://user-images.githubusercontent.com/55740/147986980-f76ee6ec-4f59-41f4-b63b-e8fa79e782ee.png)
De ce que je vois dans notre fichier des déploiements, cela a été mis en place le 15 juin.

**Comment by AntoninCurtit** [comment]
Bonsoir,
Extra ! Une bonne nouvelle pour commencer l'année, c'est parfait, merci à vous pour votre réactivité & efficacité pour la correction ! 😉

**Comment by Altonss** [comment]
Merci beaucoup pour la réponse!

> J'ai fait un petit test tout à l'heure pour vérifier, et on peut voir les attributions en bas à droite, même si cela pourrait être mieux cadré (mais c'est peut-être lié à mon navigateur) :

Sur Firefox 95 j'ai le même souci:
![image](https://user-images.githubusercontent.com/66519591/147988312-7d6a0a14-9bc9-4f1c-91d8-0cb57a9a54fb.png)

**Comment by maddingue** [comment]
Je suis aussi sur Firefox 95 Linux.
Pour être plus complet, je viens aussi de tester sur Chrome 96 Linux, ce n'est pas mieux : 
![image](https://user-images.githubusercontent.com/55740/147994445-31ab258f-cbd7-4c4e-9060-6aa0e56f23d7.png)
Et sur Safari 605.1 / iPadOS 15.2, on ne voit même plus les attributions 🙁
On va garder ça en tête, mais comme je disais plus haut, on passe par Maptiler, donc je ne sais même pas si on a la main là-dessus.

**Comment by vinber** [comment]
je peux difficilement dire si vous avez la main mais vous avez la responsabilité de votre site :D

**Comment by AntoninCurtit** [comment]
Vous avez un lien pour tester la carte ? Ou il faut obligatoirement un compte ?

**Comment by Altonss** [comment]
> Vous avez un lien pour tester la carte ? Ou il faut obligatoirement un compte ?

Il faut créer un compte

**Comment by maddingue** [comment]
> je peux difficilement dire si vous avez la main mais vous avez la responsabilité de votre site :D

Certes, mais quand il y a 3 ou 4 niveaux d'indirection, ça ne simplifie pas les choses, en particulier pour débugguer.
En pratique, on utilise le widget [Leaflet](https://leafletjs.com/) pour faire appel à MapTiler (et donc OSM), dans sa [version ClojureJS](https://clojars.org/cljsjs/leaflet).

En fouillant dans le CSS généré, je vois qu'en modifiant le `padding-bottom` de `.leaflet-control-attribution` pour ajouter 5px, le texte devient visible. Je vais ouvrir un ticket en interne, voir si les devs peuvent faire ce changement. Tant qu'à faire, on peut en profiter pour faire ajouter un lien vers OSM. Y a t-il un lien préférable ? le [site direct](https://www.openstreetmap.org/) ? la page [à propos](https://www.openstreetmap.org/about) ? autre ?

**Comment by Altonss** [comment]
> Tant qu'à faire, on peut en profiter pour faire ajouter un lien vers OSM. Y a t-il un lien préférable ? le [site direct](https://www.openstreetmap.org/) ? la page [à propos](https://www.openstreetmap.org/about) ? autre ?

En général c'est ce lien ci qui est utilisé: https://www.openstreetmap.org/copyright
Comme sur https://www.openstreetmap.org

**Comment by vinber** [comment]
@maddingue ce n'est pas moi qui peut vous aider sur du code (du moins c'est préférable pour vous :D )

> En général c'est ce lien ci qui est utilisé: https://www.openstreetmap.org/copyright

oui je confirme
