### ISSUE TITLE
Site de la ville d'Annemasse - Pas d'attribution

### ISSUE THREAD

**Issue by alkino** [osm-fr/attributions#98]
**Description**

https://www.annemasse.fr/information-transversale/annuaires/annuaire-des-associations/cartographie-des-associations
Formulaire de contact : https://www.annemasse.fr/informations-pratiques/contact

**Comment by alkino** [comment]
Contacté via le formulaire le 16 novembre 2021

**Comment by cayenne17** [comment]
"page introuvable" sur le lien du premier message.

J'ai trouvé une URL où il y a une carte et elle n'a pas de mention OSM : https://www.annemasse.fr/information-transversale/annuaires/annuaire-des-associations/cartographie-des-associations

@alkino est-ce qu'il serait possible de mettre à jour le lien dans le premier message ?

**Comment by alkino** [comment]
Chez moi les deux liens fonctionnent.

**Comment by alkino** [comment]
Mis à jour

**Comment by Jean-BaptisteC** [comment]
Contacté ce jour via le formulaire de contact

**Comment by Jean-BaptisteC** [comment]
Réponse ce jour
![share_7929570097819456769](https://github.com/user-attachments/assets/d14d27cd-4a5a-4f77-abda-960fa05a4c7c)

**Comment by Jean-BaptisteC** [comment]
Corrigé 
![image](https://github.com/user-attachments/assets/6c632c71-d154-4857-94c2-94687ad51e8b)
